### PR TITLE
Update emerald-themes

### PR DESCRIPTION
**Pull request by ThanosApostolou**
Update **emerald-themes** to version **0.8.14**. It wouldn't hurt if it was removed completely from the repositories because the AUR package is well maintained.

I also deleted the **emerlad0.9** pkgbuild in order to clean the package list, since it's no longer maintained so there's no chance that it might be needed in the future.

### CODE REVIEW

**Comment by Ste74** [comment]
Maybe seem we have forgot this .. Have you tested ? It is fine @ThanosApostolou

**Comment by ThanosApostolou** [comment]
Yep it works fine. But it seems kinda pointless to have **emeral-themes** in manjaro repositories, without having any of the rest **emerald-** packages. So, maybe it's better to remove it and let the users install it from AUR.

**Comment by oberon2007** [comment]
Yes, leave it an AUR package makes sense... :)

**Comment by Ste74** [comment]
Okk , remove it ..

**Comment by Ste74** [comment]
https://github.com/manjaro/packages-community/commit/d1ac753e7dc8fe68f12f14ee846e64442a7a4031
https://github.com/manjaro/packages-community/commit/d1ac753e7dc8fe68f12f14ee846e64442a7a4031

**Pull request closed without merging**
