### PR TITLE
update MS-Office online

### PR DESCRIPTION
**Pull request by codesardine**
Package needs a new sha and pkgbuild needs to be finish as im not shure what im doing with sed.
Made a guide [here](https://forum.manjaro.org/t/jak-framework/45067) for settings.json options @philmmanjaro

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Can you rebase your made changes to my modifications? https://github.com/manjaro/packages-community/commit/9b05c506e531439caae71104b022a81f486ff3c8 @codesardine

**Comment by codesardine** [comment]
I think this should do it, if something is not working let me know. @philmmanjaro 

Any url in "same_frame" will open in the same window, everything else will open in a new window.

**Comment by codesardine** [comment]
forgot to mention jak also needs a rebuild for this to work

**Comment by oberon2007** [comment]
There are still some merge conflict markers in the code that need to be removed, like e.g.
```
=======
>>>>>>> df2eea01c6ed24033cd873cfa9e2eacd0a5dc1e8
```

**Comment by oberon2007** [comment]
K :wink: :+1: 
https://github.com/manjaro/packages-community/commit/3f647422d6b4160fbdeabca88657308bee18da30

**Comment by codesardine** [comment]
i removed git junk and had to fix url let see if this works @oberon2007

**Comment by codesardine** [comment]
ok fixed its building now @oberon2007

**Comment by oberon2007** [comment]
What about version? Should we just bump pkgrel?

**Pull request merged**
