### PR TITLE
Update hyper stable

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by jonathonf** [comment]
Why is an epoch change needed here anyway? Why was one introduced back here: https://github.com/codesardine/packages-community/commit/a89f5737a1a21c2141cd87f02a25b88eeda31f2a#diff-88bc577e9acac9d5c27d19ac70e066b2 ?

There are too many things wrong with this PKGBUILD, e.g. empty variables.

Reading and following the Arch packaging standards would be a good thing for Manjaro contributors too. We need to have a proper discussion about this so we can maintain a consistent standard.

IIRC there's an Arch packaging class they do via IRC. Might be worth looking into.

**Comment by codesardine** [comment]
@philmmanjaro introduced the epoch back then, how you guys recommend doing this? @Ste74  @jonathonf

**Comment by jonathonf** [comment]
One approach to avoid an epoch this time round:

```
$ vercmp 1 2
-1

$ vercmp 2.0.0 2.0.0.canary
-1

$ vercmp 2.0.0.0 2.0.0.canary
1
```

In future, add "pre-release" tags directly onto the `pkgver`, i.e.

```
$ vercmp 2.1.0 2.1.0canary
1
```
so 2.1.0 will replace 2.1.0canary. This avoids the need for an epoch in future.

**Comment by Ste74** [comment]
I like your method :)

**Comment by Ste74** [comment]
@jonathonf tried to build hyper with pkgver 2.0.0.0 but epoch array still remain the main version .. 
i will upload the 2.0.0 and remove the version with epoch . After we follow your suggestion example 2.1.0canary

**Comment by codesardine** [comment]
There is a more recent  canary version available, I was thinking you guys prefer stable @ste74

**Pull request closed without merging**
