### PR TITLE
Update jade-desktop-git

### PR DESCRIPTION
**Pull request by codesardine**
Let me know if it needs changes (Not realy an expert packager its all about trial and error)

### CODE REVIEW

**Comment by Ste74** [comment]
Why pkgrel=6 ? You already release this ? If not change in pkgrel=1 and also the pkgver=0.3.26 : have you put manually this or automatically print via makepkg -od ?

**Comment by codesardine** [comment]
everytime i make a change in the PKGBUILD this goes a version up pkgrel=6
pkgver=0.3.26 this one is manual the 3 was missing in previous version meaning 3 iteration of the application (i had 2 versions before that were never released) patch 26 or fix 26, I made 26 changes, wen it achives a stable state will be 1.3.26

**Comment by Ste74** [comment]
Ok.. but this is in contrast with a git release.. your system is like a point release so you have to do the release in your repo and we can take it . The right revision for a git versioning is like @philmmanjaro do . It print the commit changes... what you prefer ? Is not a problem change the versioning if you do the point release...

**Comment by codesardine** [comment]
this version number 0.3.26+git release 
or 0.3.+git release 
or just git release 
this is not a issue for me as i control version from a file in the application .
as i said earlier am not a big expert in this stuff. So do what you think it is the best option.

**Comment by Ste74** [comment]
well , try this example : 
```
pkgver() {
  cd "$srcdir/$_pkgname"

  local v_ver=$(awk -F , '/^AC_INIT/ {gsub(/[\[\] -]/, ""); print $2}' configure.ac)

  printf "$v_ver.r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
}
```
adjust what is needed , in this example we check the version into configure.ac .. modify what is need no tested , is a draft .. but i think is what you want ..

**Comment by codesardine** [comment]
configure scripts is not in my skill set, im more of a web guy.

this line should be replaced -- depends=('python-jade-application-kit' 'jade-menu-data' 'python-xdg' 'baobab')

by this -- depends=('python-jade-application-kit' 'jade-menu-data' 'python-xdg')

and this 
provides=('jadesktop' 'jade-dashboard')
replaces=('jadesktop' 'jade-dashboard')

by this
provides=('jade-dashboard')
replaces=('jade-dashboard')

baobab is not needed anymore it was removed from the code and jadesktop was the old name, but that was not in manjaro repos so it can be removed.
everything else in the PKGBUILD should work as it is now.

**Comment by Ste74** [comment]
let me work on it ;)

**Comment by Ste74** [comment]
@codesardine please check if ok . Now we parse the file application-settings.json to match your version release automatically (thank you @Chrysostomus  😉) . 
https://github.com/manjaro/packages-community/commit/eca82b9da5d3ea9af8becd59e9e2c4dff08091e9
changed also what you have request ...

**Comment by codesardine** [comment]
this works perfect, just tested and it builds @Ste74 @Chrysostomus  tanks

**Pull request merged**
