### PR TITLE
Moka icon theme modified pkgbuild

### PR DESCRIPTION
**Pull request by Ste74**
Related on this if you think add in our repository
https://forum.manjaro.org/index.php?topic=30884.msg259381#msg259381

### CODE REVIEW

**Comment by oberon2007** [comment]
Would you like to use them on one of your ISOs?

**Comment by Ste74** [comment]
Is a official icon set in budgie. This set is more popular. I have create
this because 400 mb for dowload and other 3 set for dependence is illogic.
At your discretion. I can also upload in aur  ^_^
Il 27/feb/2016 19:48, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
If you use it in your budgie we shall adopt it of course. Otherwise I think in the AUR many people will be happy about it! :smile:

**Comment by Ste74** [comment]
Ok...please merge it. When i solve the Firefox problem i release it. But in
cinnamon Firefox start whit the right manjaro home page? I have open an
issue because ff recreate a profile folder :(
Il 27/feb/2016 20:35, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
OK :) I'll remove the "-manjaro" and the conflicts according if you agree. It's actually still the same icon-theme, right? No manjaro branding or anything like that added ;)

**Comment by Ste74** [comment]
Yes is original only removed the folder contain doc and copyright . I think
not necessary if license is present in pkgbuild .
Il 27/feb/2016 20:52, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
I'm quite happy that I have a faster internet package since yesterday... :stuck_out_tongue_winking_eye:

**Comment by Ste74** [comment]
Lucky man :wink:

**Pull request merged**
