### PR TITLE
Update brisk-menu to version 0.4.0

### PR DESCRIPTION
**Pull request by ThanosApostolou**
Now brisk  menu shows applications from the Contol Center! Also, now brisk menu works with the <kbd>Super</kbd> key! Yeah!!!! 😃

### CODE REVIEW

**Comment by Ste74** [comment]
Yep , big release :) thank you

**Comment by ThanosApostolou** [comment]
@Ste74 If you have time, can you try to update mate-tweak too (latest versions are 17.10.2 with ubuntu-mate-settings 17.10.6)? I've seen that the AUR PKGBUILD has been updated to 17.10.1. However, when I tried it myself, even thought it builds fine, the application just crashes when I try to switch panel layouts (tried both mate-tweak 17.10.1 and 17.10.2). So maybe you have better luck 😛

**Comment by Ste74** [comment]
The pkg in our repo work fine ?

**Comment by ThanosApostolou** [comment]
Yeah version 17.04.2 works fine... It's just because the AUR package got updated, I thought it would be nice to update it on manjaro too. If you can't make it work with the newer versions, then better keep it in the current version. In the future, we may need to search for new patches, or maybe ask the AUR maintainer to work together (I haven't tried it on pure arch, but I believe that it will crash there too).

**Comment by Ste74** [comment]
LOL you have misunderstanding me .. update is lways better , i ask only for curiosity and for prevent problem 😉 .. have you try to run in a terminal ?

**Comment by ThanosApostolou** [comment]
No I didn't do many tests (I'm spending more time messing around with Fedora lately 😛 ) but I might try again tomorrow.

**Comment by ThanosApostolou** [comment]
@Ste74 The error I get on terminal after I change a panel layout, is:
```
(mate-tweak:1759): GLib-GIO-ERROR **: Settings schema 'org.mate.interface' does not contain a key named 'gtk-shell-shows-menubar'
Trace/breakpoint trap (core dumped) 
```

I left a comment on the AUR package too since this is happening with the AUR PKGBUILD as well (which also has the mutiny patch which we have removed).

So, since you are the official maintainer (and that gives you some prestige 😛 ), maybe you should contact Martin Wimpress or report an issue at the bitbucket page (https://bitbucket.org/ubuntu-mate/mate-tweak) in order to figure this out.

*P.S. I know that you are busy now with the Gnome edition, so no need to hurry (the current version works fine after all). If you need any additional help/testing then tell me*

**Pull request merged**
