### PR TITLE
add manjaro webdad packages

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by codesardine** [comment]
Before merging this should I put his on .xinitrc, is the only way i can see for updating user configurations?
any better way of doing this?

for homedir in $HOME/*; do cp -r /etc/skel "$homedir"; done

**Comment by philmmanjaro** [comment]
@codesardine: if you have added some to `/etc/skel` it will be automatically added to the user on creation. Manually you can copy it as written by you above.

**Comment by codesardine** [comment]
I have files in /etc/skel
but if issue updates the end user wont get them in their home folder after installing, so how do i get around that?
using .xinitrc or there is a better way?

**Comment by philmmanjaro** [comment]
Gimme an example of a situation you need to add new files to an existing user when updating. If it is a fixed folder we can use a **pacman** hook for it. So if the content changes somehow it will trigger to do stuff.

**Comment by codesardine** [comment]
for example the custom thunderbird theme, or the custom hyper.js file

**Comment by codesardine** [comment]
Need to rework this further

**Pull request closed without merging**
