### PR TITLE
Update pacli and add vertex-maia-gtk3

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by Chrysostomus** [comment]
@oberon2007 Vertex-maia-gtk3 is for building bspwm image without gtk2 being pulled in. It is the same as normal vertex-maia, but without gtk-engine-murrine.

**Comment by oberon2007** [comment]
There are a few more adjustments needed for **vertex-maia-gtk3**: First of all folder name needs to correspond to pkgname :stuck_out_tongue_winking_eye:, also it needs to conflict with **vertex-maia-themes** pkg. And I think there is more stuff you do not want to install ... metacity, gtk3 assets including the image files copied at the end of the PKGBUILD, xfwm4 whiskermenu and panel stuff also doesn't make much sense without gtk3 I think, does it?
Also please remove **PKGBUILD.old** here. This is just for reference with the original.

**Comment by Chrysostomus** [comment]
Okay. Sorry, was being lazy and did not do the research :)

**Comment by Chrysostomus** [comment]
Okay, I made some adjustments. I kept most of the stuff execpt for the whiskermenu patch. For most people it should work like the original if they have gtk-engine-murrine installed due to the some other package.

**Comment by Ste74** [comment]
Oberon say 
>  gtk3 assets including the image files copied at the end of the PKGBUILD, xfwm4 whiskermenu and panel stuff also doesn't make much sense without gtk3 I think, does it? Cinnamon, gnome-shell, Firefox, Chrome ... ? :wink: Square theme? Palemoon?
Are you sure ? example when firefox add complete gtk3 support it will working ?

**Comment by Ste74** [comment]
Oops I misread the whole story sorry :stuck_out_tongue_winking_eye: .. ok ..

**Comment by oberon2007** [comment]
@Chrysostomus !
pacli:
```
==> Starting package()...
cp: cannot stat '/build/pacli/src/pacli/pacman.d': No such file or directory
==> ERROR: A failure occurred in package().

**Comment by Chrysostomus** [comment]
Okay, I'll look into it. I think I know where I made a mistake.

**Comment by oberon2007** [comment]
There is no **/etc/pacman.d** in the repo. Maybe you just forgot to remove it from the PKGBUILD?

**Comment by oberon2007** [comment]
I don't see how it makes sense to install the whole gtk2 folder in the vertex gtk3 package - we have the regular package for that I think ...

**Comment by Chrysostomus** [comment]
That makes sense. But frankly, the pkgbuild is mighty complex for me to weed out all the gtk2 stuff, and would involve a lot of testing, trial and error. Would you have possibility to help with it? I imagine it would be faster for you to do, since you have tinkered with this before

**Pull request merged**
