### PR TITLE
thermald 1.5.3

### PR DESCRIPTION
**Pull request by FadeMind**
`Minor change to PCH sensor support.`

@oberon2007 @philmmanjaro

### CODE REVIEW

**Comment by Ste74** [comment]
@oberon2007 how does it work ? If I run a merge how long can I let pass before putting on Boxit the binary?

**Comment by oberon2007** [comment]
As long as you like theoretically. The PKGBUILD repo and boxit are not connected...

**Comment by Ste74** [comment]
> The PKGBUILD repo and boxit are not connected...
this i know :wink:

**Comment by oberon2007** [comment]
Yes. So what is your question? :wink: You just merge it when you are actually going to build it... But it would also be possible that you merge it to show that you are going to build it and it might be that a complication occurs and it takes longer ...

**Pull request merged**
