### PR TITLE
bumblebee: adding workaround for libglvnd

### PR DESCRIPTION
**Pull request by FadeMind**
Original: https://github.com/Bumblebee-Project/Bumblebee/pull/845

Merged in 
https://github.com/FadeMind/Bumblebee/commit/0851da6818e265d354d61947021c512f2e51ffce

Reference: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/bumblebee&id=a9569bdd93b30be222f701245b5ff1dac10fbf34

@oberon2007  @philmmanjaro @Kirek

### CODE REVIEW

**Comment by Ste74** [comment]
Pushed in boxit tonight , thank you :smile:

**Comment by Strit** [comment]
A few people have issues with this commit:
https://forum.manjaro.org/t/primus-could-not-load-gpu-driver/19211

**Comment by FadeMind** [comment]
@Strit IMO is issue with KERNEL directly, not this commit.

**Comment by Strit** [comment]
Yeah, that could be. They just mentioned that it was reversed by using previous version.

**Pull request merged**
