### PR TITLE
pacui: version 1.10.3

### PR DESCRIPTION
**Pull request by excalibur1234**

### CODE REVIEW

**Comment by Ste74** [comment]
@excalibur1234 I migrated the package: https://gitlab.manjaro.org/packages/community/pacui
please create an account in gitlab.manjaro.org to get the necessary rights

**Comment by excalibur1234** [comment]
i have created my account a while ago - same name as here.
can you give me access to packages-community (or just the pacui package)?

**Comment by Ste74** [comment]
Done.. check if it work for you

**Comment by excalibur1234** [comment]
i can clone pacui's repo using ssh and have access to a package group. 
thanks.

i will test to upload a new PKGBUILD to gitlab.manjaro.org (instead of github) whenever i release the next version of pacui.

**Pull request merged**
