### PR TITLE
Update hyper

### PR DESCRIPTION
**Pull request by codesardine**
Hyper finally hit stable
https://github.com/zeit/hyper/releases/tag/2.0.0

### CODE REVIEW

**Comment by Ste74** [comment]
Hi @codesardine are you sure with your pkgbuild ? No build or other command ? 
According to this https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyper
i think you have to modify a little :wink:

**Comment by codesardine** [comment]
@Ste74  I am not sure, I copy pasted from the AUR, Will have a look after dinner

**Comment by codesardine** [comment]
Hi @Ste74  I having trouble with the hyper package from the AUR its saying libnsl cannot be installed as files alredy exist in the hdd

**Comment by philmmanjaro** [comment]
Which files? Did you checked with `pacman -Qo <file>` to see which installed package might own it?

**Comment by codesardine** [comment]
/usr/include/rpcsvc/nis_callback.h is owned by glibc 2.26-11
I am on unstable branch

libnsl: /usr/include/rpcsvc/nis.h exists in filesystem
libnsl: /usr/include/rpcsvc/nis.x exists in filesystem
libnsl: /usr/include/rpcsvc/nis_callback.h exists in filesystem
libnsl: /usr/include/rpcsvc/nis_callback.x exists in filesystem
libnsl: /usr/include/rpcsvc/nis_object.x exists in filesystem
libnsl: /usr/include/rpcsvc/nis_tags.h exists in filesystem
libnsl: /usr/include/rpcsvc/nislib.h exists in filesystem
libnsl: /usr/include/rpcsvc/yp.h exists in filesystem
libnsl: /usr/include/rpcsvc/yp.x exists in filesystem
libnsl: /usr/include/rpcsvc/yp_prot.h exists in filesystem
libnsl: /usr/include/rpcsvc/ypclnt.h exists in filesystem
libnsl: /usr/include/rpcsvc/yppasswd.h exists in filesystem
libnsl: /usr/include/rpcsvc/yppasswd.x exists in filesystem
libnsl: /usr/include/rpcsvc/ypupd.h exists in filesystem
libnsl: /usr/lib/libnsl.so exists in filesystem

**Comment by philmmanjaro** [comment]
No, not on the updated version:

> pacman -Qo /usr/include/rpcsvc/nis_callback.h
/usr/include/rpcsvc/nis_callback.h is owned by libnsl 1.2.0-1
> $ pacman -Q glibc
glibc 2.27-2

**Comment by codesardine** [comment]
Im an idiot I changed to unstable to test office, chaging back to stable and updating should fix it.

**Pull request closed without merging**
