### PR TITLE
Update bpswm packages and pacli

### PR DESCRIPTION
**Pull request by Chrysostomus**
@oberon2007 these packages need rebuilding. Pacli received a major update, limepanel now supports custom menus, and mygtkmenui should not install its .desktop file.

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Bmenu needs also to be rebuilt. I discovered a major bug and fixed it.

**Comment by Chrysostomus** [comment]
And bspwm-wallpapers.

**Comment by Ste74** [comment]
build it and upload in unstable :)

**Comment by oberon2007** [comment]
Well spotted, @Ste74 ! :smile:

**Comment by Ste74** [comment]
@oberon2007 other array typo wrong  .. in pacli i see pacman-mirror i suppose you need pacman-mirrorlist ?

**Comment by oberon2007** [comment]
I think you are right! :) Also please at a line break at end of file!

**Comment by Ste74** [comment]
What do you mean ? Only a empty line at the end ?

**Comment by oberon2007** [comment]
Yes. The last line break is missing:
https://github.com/manjaro/packages-community/pull/131/files#diff-829bec5fda691cbd60ed41bb4b00864eR29

**Comment by Ste74** [comment]
Lol i did not see :wink:

**Comment by Ste74** [comment]
@oberon2007 myGtkMenu give me error whit source :\

>   de_DE.UTF-8... done
Generation complete.
 --> Time chroot_init: 1.32 minutes
==> Start building [mygtkmenui]
==> Creating clean working copy [stefano]...done
==> Making package: mygtkmenui r23.g505c53a-2 (Wed Mar  9 21:46:54 CET 2016)
==> Retrieving sources...
  -> Cloning mygtkmenui git repo...
Cloning into bare repository '/build/src/mygtkmenui'...
remote: Counting objects: 96, done.
remote: Total 96 (delta 0), reused 0 (delta 0), pack-reused 96
Unpacking objects: 100% (96/96), done.
Checking connectivity... done.
==> Validating source files with sha256sums...
    mygtkmenui ... Skipped
 --> Setting mirrorlist branch: unstable
==> **ERROR: Cannot find the git package needed to handle git sources.**
mv: cannot stat '/build/pkg/mygtkmenui-r23.g505c53a-2-i686.pkg.tar.xz': No such file or directory
==> ERROR: /build/manjaro-tools/pkg/unstable/i686/mygtkmenui-r23.g505c53a-2-i686.pkg.tar.xz does not exist!
==> Finished building [mygtkmenui]
 --> Time make_pkg: 1.72 minutes
stefano@ste74 ~/Github/packages-community $ 

what happen

**Comment by oberon2007** [comment]
You need to add
``makedepends=('git')``
:)

**Comment by FadeMind** [comment]
`makedepends=('git')` > git sources
`makedepends=('svn')` > subversion sources
`makedepends=('bzr')` > bazaar sources

Print. Save and use. :smile: 

@Ste74 @oberon2007

**Comment by Ste74** [comment]
Ah Ah .. now try if right i have build 64bit before and git is in ncap , 32 bit is new root

**Comment by Ste74** [comment]
Lol Tomasz :wink:

**Comment by FadeMind** [comment]
Lots of AUR CVS based packages (but without CVS type in name) have missed svn  type in makedepends :anger:

**Comment by Ste74** [comment]
For me is the first time i encounterd this error but now i know how to :)
thank you guys

**Pull request merged**
