### PR TITLE
libdbusmenu 12.10.3.15.04.20150410.2-1

### PR DESCRIPTION
**Pull request by FadeMind**
Update for libdbusmenu  pkgbase packages. Tested localy, All is fine.

### CODE REVIEW

**Comment by oberon2007** [comment]
What's the intention of that?
```
_pkgbase='libdbusmenu'
pkgbase="${_pkgbase}"
```
;)

and... depending on themselves? really??
```
package_libdbusmenu-gtk2() {
  depends=("${_pkgbase}-gtk2")

package_libdbusmenu-gtk3() {
  depends=("${_pkgbase}-gtk3")
```

**Comment by FadeMind** [comment]
Good point.
I just rewrited lib32 version for build native 64 bit version and did'nt look closer. Cosmetics changes. ;) I'll take care about it.

**Comment by philmmanjaro** [comment]
I think depending on its own is not needed. That we can remove. Also **_pkgbase** can be removed. I think this is from the git-package as we don't use the -git prefix.

**Comment by oberon2007** [comment]
ok. do we adopt the -gtk3 pkg now, too? we did not have it until now.

**Pull request merged**
