### PR TITLE
Mate tweak:  fix window manager not starting after login

### PR DESCRIPTION
**Pull request by ThanosApostolou**
@Ste74  This change addresses this problem: https://forum.manjaro.org/t/mate-composit-not-working-after-reboot/28903

If you see this https://github.com/ubuntu-mate/mate-tweak/issues/30, then **mate-wm** should be able to find these desktop files from **/usr/share/mate/applications**, but for some reason it doesn't. So, as a workaround I copy those files to **/usr/share/applications** (they have NoDisplay=true so they are not visible). I tried several things but I cannot find any other solution and currently I don't have any arch installation to see if the problem is happening there as well. If you have time, look into this and if there is a deeper problem maybe contact the arch maintainer (because it seems like mate-session isn't working properly). Anyway this workaround works fine.

P.S. the mate-tweak changes for the mate-panel layouts got accepted upstream and wimpy improved them a bit, so in the next mate-tweak release we should remove the patch.

### CODE REVIEW

**Comment by Ste74** [comment]
Unfortunally i can do it or see into it for a week.. i'm out .. holiday time for me .. i can check this only after 22/8 ( when come back to home )

**Comment by ThanosApostolou** [comment]
Ok no problem, I will update mate-tweak too until then. I will also see if I can do more digging and maybe figure out where the problem comes from.

**Comment by ThanosApostolou** [comment]
@Ste74 Ok all the changes have been accepted upstream, so whenever you have time feel free to build it 😃

**Comment by Ste74** [comment]
Ok.. i will do.. i'm also looking into the mate 1.19 ( not all pkgs are released in upstream )

**Comment by ThanosApostolou** [comment]
Keep in mind that 1.19 is a development release and it might have problems or cause incompatibilities with some AUR packages (maybe for example **caja-dropbox**). The next stable release will be 1.20 (odd numbers are development, even numbers are stable releases).

**Comment by ThanosApostolou** [comment]
I don't know this site, but the official info is here: http://wiki.mate-desktop.org/dev-doc

However, MATE's development is kinda slow nowadays and since the gtk3 port there are not expected any other big changes. So, the 1.19 packages which have been released until now have only a few fixes over the 1.18 ones (I haven't seen any big changes in the commits), so they are pretty stable too that's why many people prefer to use them.

MATE is always stable even when you are using the development branch 😆 😆

**Comment by Ste74** [comment]
😅 ah ah ... same of gnome 😜 .. btw uplos ( the forum before point you ) is a fork of pclinuxos but  32 bit ..

**Pull request merged**
