### PR TITLE
a little cleanup + make steam work better

### PR DESCRIPTION
**Pull request by Tids**
At first a little cleanup. 

0006-ld_library_path_fallback_x86(+_64).patch is not required anymore. we didnt have it used anyways for a long time. Also the conflict on  'tcp_wrappers' is not required anymore, manjaro dont has this one in the repo anymore.

for the native runtime i've added openssl1.0, for some games to use. Also it now depends on "steam" itself, because There is no reason to install steam-native without steam, since its not a own app, but just the runtime switch.

The biggest change in here is that i have set STEAM_FRAME_FORCE_CLOSE=0
This will change the behavior when you click X in steam from "minimize to tray" to "minimize to taskbar". The reason is that we have no real systemtray on some system, or a buggy implementation. So in this case steam will go to the background and you can not un-minimize it anymore. With this change, its always possible to unminimize it, as long as you have a taskbar.

### CODE REVIEW

**Comment by Ste74** [comment]
Seem i lost this i can work this evening with this :p .. btw , have you see the new Linux-steam-integration of solus ? 
Do you think ?

**Comment by Tids** [comment]
About the solus thing. I don't get it for real. I mean it's a switch between native and steam runtime, isn't it?

**Comment by Ste74** [comment]
Look here..

https://plus.google.com/+Solus-Project/posts/6fgNZnL95MF

https://plus.google.com/+Solus-Project/posts/YQHYeCNVzoG

**Comment by Tids** [comment]
It sounds like a re-implementation of 
http://store.steampowered.com/news/26953/
. Steam by itself can handle just fine between systemlibs an steam runtime now. 
The only problem is the first start, because that's something valve only fixes things in the client, not the initial installer and that's something I have no idea how to fix. The LSI from solus seems to be good but to much hassle for the normal user

**Comment by Ste74** [comment]
Ok , thank you for explanation since i don't use much steam ;)

**Pull request merged**
