### PR TITLE
Update from manjaro-rt repository

### PR DESCRIPTION
**Pull request by budimanjojo**
- update to rt7
- fix installation/updating not doing mkinitcpio -p
- fix grub not the name defined in kver
- a lot of changes in naming of files

### CODE REVIEW

**Comment by oberon2007** [comment]
Thank you! I'll update the package tonight :)

Am 15. Juli 2016 06:07:23 MESZ, schrieb budimanjojo <notifications@github.com>:
>- update to rt7
>- fix installation/updating not doing mkinitcpio -p
>- fix grub not the name defined in kver
>- a lot of changes in naming of files
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/manjaro/packages-community/pull/202
>
>-- Commit Summary --
>
>  * Update from manjaro-rt repository
>
>-- File Changes --
>
>    M linux-rt-manjaro/PKGBUILD (24)
>    A linux-rt-manjaro/linux-rt-manjaro.install (72)
>    A linux-rt-manjaro/linux-rt-manjaro.preset (14)
>
>-- Patch Links --
>
>https://github.com/manjaro/packages-community/pull/202.patch
>https://github.com/manjaro/packages-community/pull/202.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/packages-community/pull/202

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by budimanjojo** [comment]
Okay, but there's a question from me though. Are we ever gonna support 32 bit on this kernel? There's a guy in the forum who's using 32 bit, so I think we should decide whether to support it or not now :)

**Comment by philmmanjaro** [comment]
Does it build for 32? Building it for another architecture will need more effort. What would be the benefit of it?

**Comment by budimanjojo** [comment]
I'll try building it tonight. Because packages inside the repository should support both architectures? Is there any other package in our repository that doesn't support 32 bit?

**Comment by oberon2007** [comment]
My information always was that on a 32bit system an rt-kernel would not really be a relevant advantage. If that's the case I think building and maintaining it just for the sake of offering a package in both architectures would not be worth the effort...

**Comment by budimanjojo** [comment]
Alright then. So we'll just skip 32 bit. :) 
Did rt7 make it into the testing update today?

**Comment by oberon2007** [comment]
rt7 I still have to build now - I was away until just recently :)

**Comment by oberon2007** [comment]
What about the naming of the extramodules packages now? Can they stay what they were? I didn't have time, yet, to dive into the details of the actual changes in the kernel PKGBUILD now ... :wink:

**Comment by budimanjojo** [comment]
Okay, so they're still testing the kernel which is having issue with grub menu not showing up the full version. Hope we can get this one into testing asap. :)

**Comment by budimanjojo** [comment]
No, there's nothing wrong with extramodules.

**Comment by oberon2007** [comment]
We can think about fast-forwarding it to testing as soon as it's ready.
However for me it was never a real issue with GRUB. It's already being displayed as **4.6-rt**. Just, **manjaro-settings-manager** would display linux 4.6 as running - not sure if this will be solved now. I'll know in half an hour or so :wink:

**Comment by oberon2007** [comment]
So, GRUB is reporting the rt now as **4.6.4-1-rt7**. With **manjaro-settings-manager** we still have this situation:



The stable linux46 which I have also installed is not listed separately.
Now how can that be solved?

**Comment by budimanjojo** [comment]
Yeah, that's something we need Philm to help us with. I don't know about manjaro-settings-manager but I looked into mhwd-kernel code and we need some commits to get it showing our kernel. And I think once we did that, manjaro-settings-manager should display our kernel right. Let's have a weekend first before getting this done :)

**Comment by budimanjojo** [comment]
These are the lines in mhwd-kernel that only show linuxXX where XX is have to be number and it only searches for packages in core repository
```
kernel_repo() {
    echo "Available kernels:"
    pacman -Ss "^linux[0-9][0-9]?([0-9])$" | grep core | while read -r; do echo "   * ${REPLY:5:8}"; done
}

kernel_list() {
    echo "Currently running: $(uname -r) (${current})"
    echo "The following kernels are installed in your system:"
    pacman -Qqs "^linux[0-9][0-9]?([0-9])$" | while read -r; do echo "   * $REPLY"; done
}
```

**Comment by budimanjojo** [comment]
It looks like manjaro-settings-manager is not getting the kernel information from mhwd-kernel. So we might need to modify it there. But, do we really need it to display our kernel there? As this is a community package.

**Comment by oberon2007** [comment]
I think at least in the long run it would be desirable that it gets handled properly. With the present situation it gets a little confusing when you have both the stable and rt kernel installed.

**Comment by budimanjojo** [comment]
I see that manjaro-settings-manager code only display major and minor version of kernels. So before we modify it to show patch version, it won't recognize -rt. I don't know much about C language, so I don't know how to do that. :(

**Comment by oberon2007** [comment]
Maybe we'll have to rething the versioning once more? Will something like **4.6.4rt** work? Or, since there is only one rt version available, just **rt-MANJARO**, similar to what linux-ck does? Or **rt8-MANJARO**? I gather that mhwd-kernel would have to be adjusted to look in community repo and to allow letters in that case, or maybe the rt-kernel could somehow be added explicitly...
But where exactly does **msm** collect its information? The small print (in my screenshot) looks like what mhwd-kernel reads, but where is major and minor version read from?

**Comment by budimanjojo** [comment]
I don't think so. Here's the code:
```
QString
Kernel::version() const
{
    return m_version;
}


int
Kernel::majorVersion() const
{
    if ( m_version.isEmpty() )
        return 0;
    QStringList splitVersion = m_version.split( "." );
    return splitVersion.value( 0 ).toInt();
}


int
Kernel::minorVersion() const
{
    if ( m_version.isEmpty() )
        return 0;
    QStringList splitVersion = m_version.split( "." );
    QString aux = splitVersion.value( 1 );
    if ( aux.length() > 1 )
    {
        if ( aux.left( 2 ).toInt() == 0 )
        {
            return aux.left( 1 ).toInt(); /* return single number minor version rc 3.1rc -> 1 */
        }
        return aux.left( 2 ).toInt(); /* return double number minor version 3.12 or 3.12rc -> 12 */
    }
    return aux.toInt(); /* return single number minor version 3.1 -> 1 */
}
```
I don't think we should rename our kernel name. And mhwd-kernel is searching the package name (linux-rt-manjaro), it has nothing to do with kernel name (4.6.4-1-rt7). So all we need to do with mhwd-kernel is just like you said before, be added explicitly.
But manjaro-settings-manager is somehow checking the kernel name. And I don't think changing our kernel name is a good idea. Major and minor version in msm is shown right there in your screenshot above. But our kernel is a patched 4.6.4-1 kernel (-rt7 means patch version). So we may need to make msm to show major version-minor-patch version instead. :)

**Comment by Kirek** [comment]
You can keep the kernel name and versioning, I will adapt msm to match the special rt case.

**Comment by budimanjojo** [comment]
@Kirek That would be awesome. Thanks man :)

**Comment by oberon2007** [comment]
Thank you very much, @Kirek! That's wonderful! :) :beers:

**Comment by Kirek** [comment]
This should do it. https://github.com/manjaro/manjaro-settings-manager/commit/189111a4eaa4e8e903a88194b2189b9d3666e125.
screenshot_20160716_225625

**Comment by oberon2007** [comment]
BRILLIANT! Thank you so much! - ( First time I see a Manjaro screenshot in Catalan, btw! :laughing: )

**Comment by budimanjojo** [comment]
Thank you @Kirek! Now we need to also make the commit for mhwd-kernel?

**Pull request merged**
