### PR TITLE
Correct moka icon theme and update new release budgie desktop

### PR DESCRIPTION
**Pull request by Ste74**

### CODE REVIEW

**Comment by oberon2007** [comment]
I adjusted moka already yesterday, pushed the changes only just now, sorry! ;) Good news is that the icons are already online since last night ;)
I'll close this and update budgie locally, ok!? :)

**Comment by Ste74** [comment]
No problem, i don`t see the moka correction .... ok for budgie, thank you
man. :-)
Il 28/feb/2016 10:22, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
This? https://github.com/manjaro/packages-community/commit/1baf628498465e8420770f36cb90cab3929804a3

**Comment by Ste74** [comment]
Do you mean?
Il 28/feb/2016 10:31, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
Ah now I got it :laughing: 
You said "I don't see..." but you meant "I didn't see..." :stuck_out_tongue_winking_eye: 
All is well! Cheers!

**Comment by Ste74** [comment]
My english is perfect no :p lol...
Il 28/feb/2016 10:39, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
Moltissimo meglio del mio Italiano ... :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
