### PR TITLE
Major bugfixes to bmenu

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by philmmanjaro** [comment]
So it seems we use the current git status when building this. So no specific git hash? How do you decide which git commit you used for v0.2?

**Comment by Chrysostomus** [comment]
... I just used the latest. It seems simpler that way. But using specific hash could maybe be prudent. Can you link me a pkgbuild doing that, so I can rewrite mine based on that?

**Comment by philmmanjaro** [comment]
Take a look at the [pamac](https://github.com/manjaro/packages-extra/blob/master/pamac/PKGBUILD) PKGBUILD. There we use either a Version-Tarball or a Tarball based on a git commit hash.

**Comment by Chrysostomus** [comment]
Thanks! I'll look into it later today.

**Comment by philmmanjaro** [comment]
Yeah, take your time. I'll build the package now for you with the current set.

**Comment by philmmanjaro** [comment]
I added you now to the packagers group. So you're training wings are off now ;) Please keep in mind to do `git pull` before you push some new to the git-repos. However you need somebody still to build the packages for you.

**Comment by Chrysostomus** [comment]
Wow. Thanks. I need to start being more careful from now on then.

**Comment by philmmanjaro** [comment]
No probs. You can still send in merge request if you have some doubts. However you have to accept the invitation first.

**Pull request merged**
