### PR TITLE
Configuration files

### PR DESCRIPTION
**Pull request by Chrysostomus**
Install default configuration files to /etc/skel 
Fix package description to not be a copy of lemonpanel.

### CODE REVIEW

**Comment by Chrysostomus** [comment]
According to arch packaging standards, right place would be /etc/{sxhkd,bspwm}/
I think message would be good, because there is no man page or documentation to alert about default configs, and google search can prove fruitless as bspwm does not have default configs normally. 

I could add the desktop file that allows starting bspwm from displaymanager to this package, and edit it to copy the files to $XDG_CONFIG_HOME/ when bspwm is started unless files already exist... I think I'll do that.

**Comment by Chrysostomus** [comment]
But I wonder if I can do that... Bspwm used to not install its example bspwm-session file, but if it does nowadays it might cause a problem.

**Comment by oberon2007** [comment]
I have just checked. bspwm installes a /usr/bin/bspwm-session

**Comment by oberon2007** [comment]
... and a /usr/share/xsessions/bspwm.desktop

**Comment by Chrysostomus** [comment]
Dang. I also downloaded net edition to check if it did. 
What happens if another package tries to install same file? Does it overwrite it?

**Comment by Chrysostomus** [comment]
Okay, now I know. Installation just fails. So alternative solution is needed.

**Comment by oberon2007** [comment]
We can install your configs under different names and then use a bspwm-scripts.install script to rename the original configs to .default and after that copy the custom file to the needed place. The depencency should normally be installed before the dependant package. In the iso-profile make sure anyway you list bspwm and sxhkd before bspwm-scripts.

**Comment by oberon2007** [comment]
We can install your configs under different names and then use a bspwm-scripts.install script to rename the original configs to .default and after that copy the custom file to the needed place. The depencency should normally be installed before the dependant package. In the iso-profile make sure anyway you list bspwm and sxhkd before bspwm-scripts.

**Comment by philmmanjaro** [comment]
I simply don't get the issue here ...

**Comment by korrode** [comment]
Neither do I, and at a quick glance i already see problems with these changes.
Example:
    install -d -m644 "$pkgdir/etc/skel/.config/bspwm/"
a directory with 644 permissions will not be accessible.
Not to mention that the install command's -d parameter makes the creation of /etc/skel/ prior to /etc/skel/.config/bspwm/ pointless.

What exactly does this package do? Why is it in the repos and how do we use it? What exactly are you trying to achieve?

**Comment by Chrysostomus** [comment]
It simply copies some executable bash scripts to /usr/bin/.

The package is intented to provide 1) scripts that provide extra functionality for bspwm 2) easy and quick initial setup for bspwm. 

Bspwm does not have default configuration files, so I wanted to provide well commented defaults that make confoguring and installing bspwm more accessible to newbies.

**Comment by korrode** [comment]
Is there a particular reason why this package is in our repos rather than just on AUR?
Is it used on any of our installation media ISO's?

**Comment by korrode** [comment]
A great way to showcase this sort of thing and make it accessible to novices is by releasing Manjaro installation ISO's that use bspwm OOTB. For which your customisations would be included in the [manjaro-tools-iso-profile](https://github.com/manjaro/manjaro-tools-iso-profiles), rather than as a package.

**Comment by Chrysostomus** [comment]
It is used in my bspwm respin, and that is where the config are from. You are probably right, I'll remove the confog files from package.

Would love to upload these to AUR, but I'm not yet sure how to do it (no experience with ssh).

**Pull request merged**
