### PR TITLE
Update

### PR DESCRIPTION
**Pull request by codesardine**
last minute patch this fixes animation issues with the toggle

### CODE REVIEW

**Comment by codesardine** [comment]
sorry i just found another bug that is critical will send another pull when fixed

**Comment by philmmanjaro** [comment]
We don't need pull requests. Simply write me or @oberon2007 an email and we update it. @Ste74 might also help if needed.

**Comment by codesardine** [comment]
Ok I was not shure how it works, anyway I manage to fix it if you could rebuild tanks @philmmanjaro

**Comment by oberon2007** [comment]
Done :) https://github.com/manjaro/packages-community/commit/045164b2ed4275a3894e0355b6cb9052cd81bf7d

**Comment by codesardine** [comment]
tanks @oberon2007

**Comment by philmmanjaro** [comment]
cruise ship :smile:

**Pull request closed without merging**
