### PR TITLE
manjaro-fluxbox-settings

### PR DESCRIPTION
**Pull request by napcok**
@oberon2007

### CODE REVIEW

**Comment by oberon2007** [comment]
Looking good! :smiley: Please remove one of the xcursor-themes from dependencies. Leave only the default. The plymouth-theme I would make an optdepends, maybe.

**Comment by oberon2007** [comment]
Thank you @napcok ! **manjaro-fluxbox-settings** package is in unstable repo now:
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160307/006364.html :+1:

**Comment by napcok** [comment]
Good news :) Tkank you @oberon2007 for your help. I learned a lot.

**Comment by oberon2007** [comment]
You are more than welcome! And thank you very much for re-animating my baby! :laughing:

**Pull request merged**
