### PR TITLE
Steam update

### PR DESCRIPTION
**Pull request by Tids**
Just a little update for the client.

1. removing the KDE-workaround that is not needed (it was a Plasma-bug on my side)
2. Arch linux has added libva ad dependency, so lets follow them with this. Also we dont need to force special minimal-versions of some libs anymore.
3. patches 0006-lib_path_and_steam_runtime.patch and 0006-lib32_path_and_steam_runtime.patch are now called 0006-ld_library_path_fallback_x86.patch and 0006-ld_library_path_fallback_x86_64.patch. Because the naming was really bad before.

BTW: does anyone know why we even need

```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib"
```

or for 64 bit
```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib32"
```
?

I was unable to find a bugreport or anything for this, but a bugreport for this special function in gentoo

https://github.com/ValveSoftware/steam-for-linux/issues/3624

### CODE REVIEW

**Comment by mirh** [comment]
:\
Tfw you spent half a day thinking to have an issue with catalyst, you ultimately find out it was steam being bugged, and then you realize in days that could have been fixed. 

My educate guess is that once upon a time that might have been needed to override steam runtime or something. Now (as I reported in the manjaro libglvnd update thread) it just disturb catalyst/oldnvidia hack.

**Comment by Tids** [comment]
@mirh so in short, we dont need it anymore? I've just tried it yesterday on a manjaro-kde live with catalyst; radeon, amdgpu-amdgpu hybrid. With

```
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib32"
```
removed. All games just keep working in the same way as if I start them with this line. So for me there is no change. But I dont know how it is with Nvidia or Nvidia-hybrid (bumblebee).

**Comment by mirh** [comment]
This line is just in the steam launcher.. So I'm not really sure on why/whether it should propagate on games. 
Anyway, yes, I'd really say we don't need it. 
This is doubly superfluous since steam added its STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1 thing this january. 
>But I dont know how it is with Nvidia or Nvidia-hybrid (bumblebee).

Well, nvidia uses libglvnd.. So it has no hack on LD from our side to interfere with in the first place. 
As for bumblebee.. it always used similar tricks.

**Comment by Tids** [comment]
OK i digged in a little deeper.

this is a workaround for a bug in steam, back from 2015 
https://github.com/ValveSoftware/steam-for-linux/issues/3697

where steam was not able to start without `LD_LIBRARY_PATH` set.
https://github.com/ValveSoftware/steam-for-linux/issues/3729

This bug is not there anymore, just nobody has removed that patch from Manjaro, since it looks very important 🗡.

I have a testing version here: https://forum.manjaro.org/t/steam-please-help-to-test-a-new-version/21748 without that ldpreload and everything seems to work. i'll do some more testing and if nothing bad happens I think we're good to go to remove this patch 👍

**Comment by mirh** [comment]
Updates?

**Comment by Ste74** [comment]
If @Tids confirm this work as expected we do :)

**Comment by Tids** [comment]
^ Let's ship it without ld_library_path_fallback patches. I haven't removed them completely for now, that makes it easier to grab the pkgbuild and build it. If everything works for everyone, let's remove them with the next steam update.

@Ste74 for me, and the few users who tested it for the last weeks, everything works as expected. So let's ship it 👍 :)

**Comment by Ste74** [comment]
Done

**Comment by mirh** [comment]
If somebody could please merge manjaro/packages-multilib/pull/12 I'd be delighted.

**Pull request merged**
