### PR TITLE
add kdebase-runtime to makedepends in qtcurve for fix build in chroot

### PR DESCRIPTION
**Pull request by FadeMind**
Only qtcurve need this. I missed this.

### CODE REVIEW

**Comment by oberon2007** [comment]
We still appear to miss something more:
```
-- Could NOT find KDE4Workspace (missing:  KDE4Workspace_CONFIG) 
CMake Error at qt5/CMakeLists.txt:58 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 1.2.0) with any of the following names:
    ECMConfig.cmake
    ecm-config.cmake
  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.
```

**Comment by oberon2007** [comment]
kdebase-workspace ?

**Comment by oberon2007** [comment]
plus **extra-cmake-modules** ? ;) :D

**Comment by oberon2007** [comment]
plus **kconfigwidgets** ?

**Comment by oberon2007** [comment]
**kxmlgui**

**Comment by oberon2007** [comment]
**kdelibs4support**

**Comment by oberon2007** [comment]
**kdoctools**

**Comment by oberon2007** [comment]
Seems to build now with all of the above mentioned ;)
Not sure if they are all needed, but looks like ... maybe not kdelibs4support...

**Comment by oberon2007** [comment]
fixed now with https://github.com/manjaro/packages-community/commit/eff7abb5816e1d042bb39337062cba15aceaaef1

**Comment by FadeMind** [comment]
@oberon2007  I followed main PKGBUILD from arch. Only changed makedeps (kdebase-runtime, git), sources url. 
Compare: 
https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/qtcurve
https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/lib32-qtcurve

;)

**Comment by oberon2007** [comment]
I guess those guys - and you build more KDE pkgs than I do ... ;) my chroot is now close to 3GB ;)

**Comment by FadeMind** [comment]
@oberon2007  kdebase-workspace is not needed to build. kdebase-runtime have proper libs and don't conflict with Plasma 5.

**Comment by oberon2007** [comment]
ok https://github.com/manjaro/packages-community/commit/ff941a36231b5bf4252bdf1ee788d4a29eb57ff2 :)

**Comment by FadeMind** [comment]
@oberon2007  Please  reply  if build or not... :package:

**Comment by oberon2007** [comment]
yes. built successfully. will push everything to unstable in a few minutes.

**Pull request merged**
