### PR TITLE
keep up with upstream changes

### PR DESCRIPTION
**Pull request by budimanjojo**
Maybe you're busy @oberon2007 so I'll do it for you then :smile:

### CODE REVIEW

**Comment by oberon2007** [comment]
The thing is, we can't update the kernel to 4.6.3, because the rt-patch has not been updated, yet apparently - at least not when I checked this morning... Does it make sense to rebuild the updated extramodules against 4.6.2?

**Comment by oberon2007** [comment]
ah. sorry. I only see now that it was just the spl-zfs package :wink:

**Comment by budimanjojo** [comment]
Do we need to update to 4.6.3 in order to update this package?
Yeah mate, it's zfs :smile:

**Comment by oberon2007** [comment]
Well, nothing to update then ... :stuck_out_tongue_closed_eyes:

**Comment by budimanjojo** [comment]
Actually I'm now trying to build 4.6.3. If nothing happened during the building, I think we can bump into 4.6.3 just fine :smile:

**Comment by oberon2007** [comment]
ok, great! just send the updated PKGBUILD when you've verified that it runs ok. Thanks!

**Comment by budimanjojo** [comment]
Just got it built fine, no error at all. :+1:

**Pull request merged**
