### PR TITLE
Add gnome shell extension and related

### PR DESCRIPTION
**Pull request by Chrysostomus**
Not sure if gnome-shell-manjaro-update builds, because my test system has problems with git. @Ste74

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Tested with another system, for some reason git just hangs

**Comment by Ste74** [comment]
Let me see .. but what is unite ? i have searched but not found screenshots.. i read is a extension for look and feel of unity ? 
Btw i have created a devel branch for manjaro-desktop-settings to use .. then build a new devel pkg to do in repo for testing ..

**Comment by Chrysostomus** [comment]
Last post here has screenshots with unite enabled: https://forum.manjaro.org/t/gnome-edition-improvement-focus/22240/55

- move tray like topicons plus
- show window title in panel
- merge headerbar of maximized windows windows with top panel, put window buttons (minimize, maximize, close) in the top panel 
- move calendar to the right in the top panel

**Comment by Chrysostomus** [comment]
I'll try to figure out how to get the updater extension to build...

**Comment by Ste74** [comment]
Now build this to do in repo .. i have to correct some dependence in a chroot build 😉

**Pull request merged**
