### PR TITLE
update Webdad

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by codesardine** [comment]
cheers :+1:

**Comment by codesardine** [comment]
I am Sorry @Ste74  but I had more file conflicts. I just fixed could you rebuild again.
manjaro-webdad-settings and webdad-workspaces

**Comment by Ste74** [comment]
Done ;) https://github.com/manjaro/packages-community/commit/0e5f420f0513c1d846f65c5b1fbf51d9d3fe9c5a

**Comment by codesardine** [comment]
thanks again :+1:

**Comment by Ste74** [comment]
All fine :)

**Pull request merged**
