### PR TITLE
Run xdg-open as the calling user instead of root

### PR DESCRIPTION
**Pull request by jonathonf**

### CODE REVIEW

**Comment by Ste74** [comment]
Thank you @jonathonf 😃

**Comment by oberon2007** [comment]
Are you not missing a whitespace there?: ``sudo -u $SUDO_USER``

**Comment by jonathonf** [comment]
> Are you not missing a whitespace there?: sudo -u $SUDO_USER

It doesn't make any difference with a short flag (e.g. `ssh -p2222` is the same as `ssh -p 2222`).

**Comment by oberon2007** [comment]
ok I see 👍

**Comment by budimanjojo** [comment]
But what if the command think it's the continuation of that command? For example, when the $SUDO_USER is simply "p". Will it run the command "sudo -up xdg-open" which will return "xdg-open user not found“?

**Comment by jonathonf** [comment]
Are you thinking out loud, or have you checked that's an actual issue? It would go entirely against `sudo` behaviour if so:

```
$ sudo -up xdg-open http://www.google.com
sudo: unknown user: p
```

**Comment by budimanjojo** [comment]
I was just asking if that's possible. Sorry and thanks for clarifying it :)

**Comment by jonathonf** [comment]
No worries. :)

**Comment by Ste74** [comment]
Hi guys , i try it but no difference in pamac , no try in octopi but i think is the same .. xdg-open not work now because say xdg-open user not know or similar message.. :\ in tty all work fine but here no :( i have also try to add a policy rule in the polkit folder but nothing change .. @guinux have other idea to force the opening a browser from pamac terminal emulator ? .. 
At last via .install all work but not use the hook potentiality :\

**Comment by jonathonf** [comment]
So, when the hook fires from within Pamac there is no $DISPLAY set and `xdg-open` falls back to terminal-based browsers.

Setting `DISPLAY=:0` or similar doesn't appear to help, e.g.

```
+ DISPLAY=:0
+ xdg-open 'https://wiki.manjaro.org/index.php?title=AUR'
No protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :0
```

This might be a limitation or feature of libalpm... ?

**Comment by Ste74** [comment]
Yes this is strange ...

**Comment by Ste74** [comment]
[this]( https://fedoraproject.org/wiki/Common_F25_bugs#Running_graphical_apps_with_root_privileges_.28e.g._gparted.29_does_not_work_on_Wayland) can help us ? I not understand what have to do ...

**Comment by guinux** [comment]
This is because pamac-daemon which performs transactions is a dbus daemon. Dbus runs daemons as root whith restrictive environment variables. It's a security but also can be a trouble.

**Comment by Ste74** [comment]
I like if i can open a browser here because i think is better if we force user to know the wiki page ( only here of course not a permanent switch ) . For now i have only write a simple message https://github.com/manjaro/packages-community/commit/c8cee61061acb48ead4a029c2492708208dbd0b6 .. 
BTW i have try also to kill the pamac process using a second script shell called by manjaro-aur-support script but without success :\

**Pull request merged**
