### PR TITLE
bump to 4.8.2-rt2

### PR DESCRIPTION
**Pull request by budimanjojo**
@oberon2007 @philmmanjaro Please review guys :)

### CODE REVIEW

**Comment by philmmanjaro** [comment]
I'd suggest to update to **v4.8.3** as that version includes some security fixes.

**Comment by oberon2007** [comment]
I'll just merge it now and then release it when 4.8.3-rt gets available. So I can test it meanwhile...

**Comment by budimanjojo** [comment]
@philmmanjaro okay I'll try it this weekend :) 
@oberon2007 Thanks man, I successfully built it but haven't got time to test it out yet. Hope everything is good :D

**Comment by oberon2007** [comment]
@budimanjojo you can try, but quite likely the present rt-patch will not work for the higher $_sublevel. We're not in a hurry, I think, and can just wait until the matching 4.8.3 patch is published.

**Pull request merged**
