### PR TITLE
[snapd] Add patch to treat Manjaro like Arch

### PR DESCRIPTION
**Pull request by mati865**

### CODE REVIEW

**Comment by jonathonf** [comment]
It's not obvious from the commit what the effect of the change is. What does setting a mount directory do?

**Comment by mati865** [comment]
I've been thinking about it and it was pretty bad workaround to diverge from Arch.

The root issue is Manjaro is being treated like Ubuntu because snapd doesn't [detect it's on Arch/Fedora](https://github.com/snapcore/snapd/blob/master/dirs/dirs.go#L171).
Edited PR to fix the root cause.

There are 2 easy solutions:
- I can try push my snapd patch upstream
- Manjaro would add `ID_LIKE=arch` to it's `/etc/os-release` like here:
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
```

**Comment by mati865** [comment]
@philmmanjaro what is your opinion on preferred solution?

**Comment by mati865** [comment]
Sorry for the noise I haven't noticed snapd 2.30-2 which actually fixes standard usage things didn't hit stable yet.

So this PR will only fix tests and chroot.

**Comment by philmmanjaro** [comment]
Will update it as needed when I find time for it.

**Comment by jonathonf** [comment]
Considering Arch don't package `snapd` but we do, I think we can legitimately pick up this patch until it's applied upstream.

Upstream should probably also think about supporting Manjaro as a first-class citizen. ;)

**Comment by philmmanjaro** [comment]
@jonathonf: build it as needed. Else I'll try to catch up on it by the end of this weekend.

**Comment by jonathonf** [comment]
Builds in progress.

**Comment by mati865** [comment]
@philmmanjaro should I upstream the patch or create PR adding `ID_LIKE=arch` to `os-release`?

**Comment by philmmanjaro** [comment]
@mati865: I'd say upstream the patch ...

**Comment by jonathonf** [comment]
Packages uploaded.

**Comment by zyga** [comment]
I think this is now merged upstream and will come out in 2.31. Thank you for contributing

**Comment by jonathonf** [comment]
Looking at the discussion above, it seems that Arch have 
```
ID=arch
ID_LIKE=archlinux
```
in their `/etc/os-release`.

Manjaro is definitely "arch-like" so we should probably adopt that `ID_LIKE=archlinux` line too? (Ubuntu has `ID_LIKE=debian`.)

**Pull request merged**
