### PR TITLE
Important release for Adapta-gtk-theme

### PR DESCRIPTION
**Pull request by ceyhunnabiyev**
Bumped supported Budgie-desktop version to >= 10.4 in Adapta version [3.92.1.90](https://github.com/adapta-project/adapta-gtk-theme/releases)

### CODE REVIEW

**Comment by ceyhunnabiyev** [comment]
Yes, please look at  [this](https://wiki.archlinux.org/index.php/makepkg#Signature_checking).

**Comment by jonathonf** [comment]
Great; can you update the PKGBUILD to add the signature file to the source array?

**Comment by ceyhunnabiyev** [comment]
@jonathonf , done. Please check it..

**Comment by Ste74** [comment]
@jonathonf if you want use a gpg key for any pkgs ( if provided ) we add to discuss with the team i think .. anyway here is need also the gpg key of tista..

**Comment by Ste74** [comment]
Edit : can be this ? Maybe in a ubuntu key server ?
https://github.com/adapta-project/adapta-gtk-theme/issues/514#issuecomment-330867793

**Comment by Ste74** [comment]
@ceyhunnabiyev please try to add also this
`
validpgpkeys=('EAC0D406E5D79A82ADEEDFDFB76E53652D87398A')`

**Comment by Ste74** [comment]
Last change :p .. since this version is not released please set `pkgrel=1` ;)

**Comment by ceyhunnabiyev** [comment]
Sorry..

**Comment by Ste74** [comment]
No problem at all :D

**Pull request merged**
