### PR TITLE
Add zsh-autosuggestions

### PR DESCRIPTION
**Pull request by Chrysostomus**
Planned to be used as dependency for future manjaro-zsh-config package

### CODE REVIEW

**Comment by oberon2007** [comment]
@Chrysostomus can you please use a git-snapshot in the PKGBUILD, like for example [here](https://github.com/manjaro/packages-community/blob/master/artwork-andromeda/PKGBUILD) ?
It will be good to avoid the **git** makedepends.
``provides=('zsh-autosuggestions-git')`` is not needed and can be removed. Conflicting is enough. Also it's more the other way round, if you want to install the -git version of some software, you will need it to provide the normal one in order to be able to satisfy dependencies of other packages depending on it.

**Comment by Chrysostomus** [comment]
Now added manjaro-zsh-config.

Features:
- bash style basic prompt, exept green
- show exit status of previous command in right prompt if command failed
- xtrem style navigation (ctrl+arrow moves a word, ctrl+backspaces deletes previous word)
- fish style syntax highlighting, autosuggestion and history substring search
- colored manpages
- set base16 color themes from zshrc, many options and simple configuration
- good zsh completion

@oberon2007 Working now on that snapshot PKGBUILD; almost done. I'll update it on next git repo update.

**Comment by Chrysostomus** [comment]
Fixed now

**Comment by Chrysostomus** [comment]
@oberon2007 I would like to add manjaro-zsh-config as a option to manjaro-architect

**Comment by oberon2007** [comment]
@Chrysostomus, I'm sorry. I don't know what my brain was doing :laughing: Of course the makedepends doesn't matter at all since people will not build the pkg but install the pkg :roll_eyes: I'm changing it back :wink:

**Pull request merged**
