### PR TITLE
Create lxde-wallpapers package

### PR DESCRIPTION
**Pull request by ThanosApostolou**
I would like to create the **lxde-wallpapers** package which will have some wallpapers. The 5 which are included now are created by muser (he has a topic with wallpapers in the manjaro forum) and I have contacted him and he is ok with me including them. This package will be a dependency for **manjaro-lxde-settings**.

I see that the other similar packages (cinnamon-wallpapers, gnome-wallpapers, etc...) are using as source each maintainers' github page. Is it ok if I just upload the images here alongside with the PKGBUILD?

### CODE REVIEW

**Comment by Ste74** [comment]
I prefer ( but is a general rule ) if the wallpapers image hosted in your github account ( or muser ) if you don't want add i can add in my repo ;)

**Comment by ThanosApostolou** [comment]
Ok thx for clarifying that. I will include them in my github account and I will do the changes.

**Comment by philmmanjaro** [comment]
It is not so good to start bloating our repo with wallpapers. As @Ste74 already posted, it is best to host the images in your personal repo and link just to the raw-urls. Thx.

**Comment by philmmanjaro** [comment]
NAK. Will close this one then.

**Pull request closed without merging**
