### PR TITLE
Update Corebird to 1.5

### PR DESCRIPTION
**Pull request by FabioLolix**
New version released

### CODE REVIEW

**Comment by oberon2007** [comment]
The package was initially added for the sonar edition by @coffeeking 's request. Question is, does the edition still exist and do we need to keep the package in repos?

**Comment by FabioLolix** [comment]
Don't know if it is used in some edition, I'm using it and it was a bit behind.

**Comment by oberon2007** [comment]
I'll remove our outdated version in any case and see if anyone still needs it. Providing a non-up-to-date version doesn't make sense in any case ... 😉

**Comment by oberon2007** [comment]
closing for now

**Comment by FabioLolix** [comment]
It is in Arch repo now

**Pull request closed without merging**
