### PR TITLE
Add linux-rt kernel with all the required extramodules to community repository

### PR DESCRIPTION
**Pull request by budimanjojo**
The commits can be read in here:
https://github.com/budimanjojo/manjaro-rt
Thanks before :)

### CODE REVIEW

**Comment by budimanjojo** [comment]
folder name changed to match the package name, as suggested by korode the name of the kernel should be linux-rt-manjaro here: https://github.com/manjaro/packages-core/pull/48#issuecomment-225779049

**Comment by Ste74** [comment]
Please before commit here follow suggestion of @philmmanjaro , create own online repository ( sourceforge or other ) to test it . Manjaro support more kernel and i agree with @korrode ; really is needed support officially this particular kernel ? 
https://github.com/manjaro/packages-core/pull/48#issuecomment-225425107

**Comment by budimanjojo** [comment]
I need to know more about how the packaging in Manjaro community repository is working. So by making an online repository for the packages, is it only for first time testing? Or do I have to build them everytime I want to release new version? I have a really slow upload speed, and building all the packages for the kernel and extramodules for both architecture will become a massive ++300mb for me to upload, which is fine if this is a one time job but I'm gonna give up if I need to do it on every release.
Do we have any build server like ArchLinux has with their pkgbuild.com? Or are there anyone here a packager? Also, what's the chance of this kernel even hit Manjaro repository? I'm sorry I thought all I need to maintain is the PKGBUILDs and Manjaro will package them for me automatically.

**Comment by Ste74** [comment]
Basically yes , i can merge and upload in our repo , @oberon2007 can also but i not know how manjaro's user can be benefit with this , how user use for audio editing. Manjaro is not a specific distro target i think but i can wrong.

**Comment by budimanjojo** [comment]
Alright, then my upload speed will not be an issue now. So, I already did post a topic in the forum a while back and here's the link. I don't know how much votes do I need to get you guys consider it benefiting and how longer do I need to wait, but I'll always keep my kernel up to date until and will keep finding interested users :)

**Comment by budimanjojo** [comment]
https://forum.manjaro.org/t/anybody-want-this-kernel/4066

**Comment by oberon2007** [comment]
It looks like there is at least some interest in the community, also I guess the interest will grow when something becomes available... I find this interesting really interesting and exciting, working in the music business myself ... :stuck_out_tongue_winking_eye: 
It's just that in fact we still have to build the whole set of big packages manually, meaning about every two weeks 8^} I cannot guarantee that I will be up to that task, including some necessary bugfixes sometimes that will certainly occur every now and then...
I did not read up everything about this topic, yet - how many kernels would be be planning on delivering? Just 4.4 and 4.6 atm, or more?
Am I right that i order to build the extramodules I'd have to have the respective kernels running? That would be another problem for me, since my current hardware doesn't like anything above 4.1 - Well, I guess I could build those in the chroot still, just the clever modules buildscript will not apply for me in that case :wink: 
For me all this would maybe be feasible if we could work on this as a team, maybe @budimanjojo @oberon2007 @Ste74 and @Chrysostomus (when he's ready in the near future ;) )
What do you think, @philmmanjaro

**Comment by oberon2007** [comment]
To be completely frank it's also not a bagatelle decition to grant boxit access to someone without really knowing much about you or your history with manjaro - if you see what I mean, @budimanjojo :wink: - no offence intended! At the same time it feels like quite a huge task to just include into what everyone is already accomplishing here ... ... so, the helping hand would at the same time be more than welcome.

**Comment by oberon2007** [comment]
In any case I think all this would only really make sense if these kernel would be handled by mhwd, too. Otherwise I agree with @Ste74 that the AUR would maybe be a good place for the packages for now...

**Comment by budimanjojo** [comment]
Thanks @oberon2007. For the kernel series, I think I'll just stick with the current stable kernel, if there's a future plan for other versions, I think at the most I'm gonna do the lts series only (4.4). The reason beside I don't have so much time for all of them is because the upstream rt patches are not keeping up with kernel version other than lts and current stable, even the 4.1 kernel is behind 5 minor releases from the Manjaro linux41 series. I can build and upload the modules if you find it annoying to chroot and stuffs as they are not so big to upload :) 
What is boxit? I don't need access to it, I will keep my github repo up to date and do a pull request everytime the core linux46 is updated in Manjaro. I promise to keep the PKGBUILD up to date for you guys here. :) 
No offense received mate, I admit I'm new in Manjaro development contribution and I'm really still in learning process. ☺

**Comment by budimanjojo** [comment]
Integrating into mhwd-kernel still needs work for sure. I checked into the source code and found out it will only detect kernels with linux[1-9][1-9], while my kernel will be named linux-rt-manjaro. It used to be linuxrt but @korrode suggested me to change it into linux-rt-manjaro to match with the other community packages adopted from AUR. I wonder if a simple adding the mhwd-kernel source code can fix this problem. But if you guys want this kernel to be available just in AUR, I really don't mind. I understand it ☺

**Comment by oberon2007** [comment]
If it's just one kernel, I think I could do the packaging - at least most of the time and then we could also share... **boxit** is our package-to-server-management. Whoever has acces to it has access to all of manjaro's packages on the server - so ... a mighty tool so to speak :stuck_out_tongue_winking_eye:

**Comment by budimanjojo** [comment]
Nice. 🙋
So I'll do the PKGBUILD and patching stuffs, you'll  handle the packaging. That will be the best of both world. ☺
Such a mighty tool must require a deep knowledge and I don't think I can manage to do it. I'm really new in development stuffs mate.

**Comment by Ste74** [comment]
Ok @oberon2007 this have sense :stuck_out_tongue_winking_eye: only I would not burden the work of Philip ( the boss ) with the kernel if born a mistake :wink:

**Comment by oberon2007** [comment]
I've made a test build here of the kernel. Seems to run fine. However there appear to be some problems when trying to build the extramodules. Before I dig deeper into this, have you actually tried building them, @budimanjojo ? :wink: 
Also I have a question for the more experienced: Is it enought to have the respective kernel installed in order to build extramodules? Or does is need to be actually running?

**Comment by Ste74** [comment]
Have you build whit -n option?
Il 15/giu/2016 19:41, "Bernhard Landauer" <notifications@github.com> ha
scritto:

**Comment by oberon2007** [comment]
No. The extramodules script actually builds with makepkg. In any case there is - apart from some checksums that apparently still need updating - also for example a dependency conflict between **broadcom-wl-dkms** and  **linux-rt-manjaro-broadcom-wl** ...

**Comment by budimanjojo** [comment]
@oberon2007 You don't need the kernel to be running in order to build them. I have tried the Nvidia and virtualbox modules and they work fine. Sorry I'm just awake, it's 3 a.m in the morning here in my country ☺
Now I'm gonna try building all the modules. I'll update all the checksums.
@Ste74 I'll test the kernel before releasing the PKGBUILD too because I'm also using it. This will at least ensure the kernel is working. ☺

**Comment by oberon2007** [comment]
Good morning! :stuck_out_tongue_winking_eye: 
I'm currently trying to build the modules separately, too.
What I found so far:
**catalyst** has a problem, but I've just tried building the official manjaro 4.6 one and it has the same failure with that amd-calalyst script in prepare() - @philmmanjaro will know more about how he fixed that for the latest 4.6 build :wink:
**ndiswrapper** has a little type in build(), where
``_extramodules=extramodules-4.4-rt-MANJARO`` needs to be _extramodules=extramodules-4.**6**-rt-MANJARO
**nvidia-304xx** fails for me with
```
make[2]: *** [Makefile:1429: _module_/home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/nvidia-304xx/src/NVIDIA-Linux-x86_64-304.131-no-compat32/kernel] Error 2
NVIDIA: left KBUILD.
nvidia.ko failed to build!
make[1]: *** [Makefile:255: module] Error 1
make: *** [makefile:59: module] Error 2
```
**nvidia-340xx**, **r8168**, **rt3562sta**, **spl_zfs**, **tp_smapi**, **vhba-module** and **virtualbox-modules** I haven't tried, yet ... :wink:

**Comment by budimanjojo** [comment]
@oberon2007 I know what's causing the conflict in broadcom-wl now, but I think it's intended? My code is based on the linux46-extramodules here: https://github.com/manjaro/packages-extra/blob/master/linux46-extramodules/broadcom-wl/PKGBUILD and I think that's intended by default. You need broadcom-wl to build the module, and then you remove it because the module provides broadcom-wl.
Okay, mate. Wait for me. I'm still in b section :smile:

**Comment by oberon2007** [comment]
**nvidia-340xx** misses a closing quote in line 26 :wink:

**Comment by oberon2007** [comment]
also in **nvidia-340xx** checksum for the added patch is missing.

**Comment by oberon2007** [comment]
hm, and **nvidia-340xx** altogether:
```
The kernel you are installing for is a PREEMPT_RT kernel!

The NVIDIA driver does not support real-time kernels. If you 
are using a stock distribution kernel, please install 
a variant of this kernel that does not have the PREEMPT_RT 
patch set applied; if this is a custom kernel, please 
install a standard Linux kernel.  Then try installing the 
NVIDIA kernel module again.

*** Failed PREEMPT_RT sanity check. Bailing out! ***
```

**Comment by oberon2007** [comment]
build() of **r8168** needs some fixing...

**Comment by oberon2007** [comment]
no joy with **spl_zfs**, yet.

**Comment by oberon2007** [comment]
**tp_smapi** has a problem with that variable in line 37

**Comment by oberon2007** [comment]
The rest builds fine already :+1:

**Comment by oberon2007** [comment]
...and where I live it's time to go to bed now :wink: :smiley:

**Comment by budimanjojo** [comment]
Everything is fixed now, this actually happen because I based the extramodules from linux44-extramodules (because I started from linux44).
Now everything seems to build fine on my system. 
Summary time:
Nvidia-304xx seems like doesn't like realtime at all
spl_zfs gave me errors, I'll look at the error log tonight because where I live it's time to work now :laughing:

**Comment by oberon2007** [comment]
Great! All looking very good already.
* about **catalyst** lets see what happens with the official one
* **nvidia-340xx** will just not work for the RT kernel
* with **spl-zfs** we still have an issue. The official one builds ok and the diff looks perfectly fine:
```
4,5c4,5
< _linuxprefix=linux46
< _extramodules=extramodules-4.6-MANJARO
---
> _linuxprefix=linux-rt-manjaro
> _extramodules=extramodules-4.6-rt-MANJARO
9c9
< pkgrel=2
---
> pkgrel=1
35c35
< package_linux46-zfs(){
---
> package_linux-rt-manjaro-zfs(){
50c50
< package_linux46-spl(){
---
> package_linux-rt-manjaro-spl(){
```
But I get a bunch of errors like:
```
/home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build/include/sys/rwlock.h:55:41: error: ‘struct rw_semaphore’ has no member named ‘wait_lock’
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
```
and build fails with
```
make[5]: *** [scripts/Makefile.build:292: /home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build/module/splat/splat-rwlock.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build/module/splat/splat-atomic.o
make[4]: *** [scripts/Makefile.build:440: /home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build/module/splat] Error 2
make[3]: *** [Makefile:1429: _module_/home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build/module] Error 2
make[3]: Leaving directory '/usr/lib/modules/4.6.2-1-rt5-MANJARO/build'
make[2]: *** [Makefile:11: modules] Error 2
make[2]: Leaving directory '/home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build/module'
make[1]: *** [Makefile:588: all-recursive] Error 1
make[1]: Leaving directory '/home/bernhard/manjaro/rt/linux-rt-manjaro-extramodules/spl_zfs/src/dkms/spl/0.6.5.7/build'
make: *** [Makefile:469: all] Error 2
```

**Comment by budimanjojo** [comment]
What is spl_zfs exactly? Is it possible that the wait_lock error related to the nvidia patch that I add into the kernel? Nvidia driver has a weird bug with rt kernel that sometimes just freeze the screen (happened to me twice before applying the patch). Tonight I'll try building the kernel again without the patch and see if spl_zfs works again. 
Here's the nvidia patch: https://github.com/budimanjojo/manjaro-rt/commit/6afb03709e583548486f814aec332d382f1a080e

**Comment by budimanjojo** [comment]
Found something here: https://github.com/zfsonlinux/spl/issues/486
Seems like another thing is not gonna work here, unless I change the PREEMPT_FULL config to PREEMPT_STB. What do you guys think?

**Comment by oberon2007** [comment]
So from what I read there it doesn't seem to make much sense to set PREEMPT_RTB, right?

> RT Basic (CONFIG_PREEMPT_RTB) only enables some preparatory changes for RT but doesn't enable RT at all - so it pretty much resembles stock CFS scheduler and kernel behavior

I'd just wait for a fix at their end and just not provide the **spl_zfs** module for now.
If that's ok with you, @philmmanjaro I'd push the kernel and the available extramodules to unstable branch tonight (CET :wink: ) for whoever would like to test this. Objections anyone?

**Comment by oberon2007** [comment]
@philmmanjaro what's the secret about unzipping/running that **amd-catalyst-15.9-linux-installer-15.201.1151-x86.x86_64.zip** file?
``/bin/sh: ./AMD-Catalyst-15.9-Linux-installer-15.201.1151-x86.x86_64.run: No such file or directory``

**Comment by budimanjojo** [comment]
Thanks, man. I wonder if there's anything I should test it out? The main advantage of rt kernel is for better audio, so anyone with a good knowledge about audio quality?

**Comment by oberon2007** [comment]
Well just tell the bus-load of people on the forum, who are eagerly waiting for the RT-kernel!! :wink:

**Comment by budimanjojo** [comment]
Okay, let me know when it's up there 😀

**Comment by oberon2007** [comment]
So, regarding **catalyst** I found this in the AUR PKGBUILD:
```
url_ref="http://support.amd.com/en-us/download/desktop?os=Linux+x86"
DLAGENTS="http::/usr/bin/curl --referer ${url_ref} -o %o %u"
```
I don't really understand what it does or why @philmmanjaro apparently doesn't need that, but in any case, when I add this, the module builds for me, too :smile:
Will upload everything now...

**Comment by oberon2007** [comment]
in unstable now:
```
[New Packages]
linux-rt-manjaro-4.6.2_rt5-1-x86_64.pkg.tar.xz
linux-rt-manjaro-acpi_call-1.1.0-1-x86_64.pkg.tar.xz
linux-rt-manjaro-bbswitch-0.8-1-x86_64.pkg.tar.xz
linux-rt-manjaro-catalyst-1:15.201.1151-1-x86_64.pkg.tar.xz
linux-rt-manjaro-headers-4.6.2_rt5-1-x86_64.pkg.tar.xz
linux-rt-manjaro-ndiswrapper-1.59-1-x86_64.pkg.tar.xz
linux-rt-manjaro-nvidia-1:364.19-1-x86_64.pkg.tar.xz
linux-rt-manjaro-nvidia-304xx-304.131-1-x86_64.pkg.tar.xz
linux-rt-manjaro-nvidiabl-0.88-1-x86_64.pkg.tar.xz
linux-rt-manjaro-open-vm-tools-modules-2:2013.09.16-1-x86_64.pkg.tar.xz
linux-rt-manjaro-r8168-8.040.00-1-x86_64.pkg.tar.xz
linux-rt-manjaro-rt3562sta-2.4.1.1_r3-1-x86_64.pkg.tar.xz
linux-rt-manjaro-tp_smapi-0.41-1-x86_64.pkg.tar.xz
linux-rt-manjaro-vhba-module-20140629-1-x86_64.pkg.tar.xz
linux-rt-manjaro-virtualbox-guest-modules-5.0.20-1-x86_64.pkg.tar.xz
linux-rt-manjaro-virtualbox-host-modules-5.0.20-1-x86_64.pkg.tar.xz
```

**Comment by oberon2007** [comment]
Oops, forgot **broadcom** and **rt3562sta** - they're coming, too!

**Comment by oberon2007** [comment]
[New Packages]
linux-rt-manjaro-broadcom-wl-6.30.223.248-1-x86_64.pkg.tar.xz

**Comment by budimanjojo** [comment]
@oberon2007 Okay, thanks man. Gonna open up a thread about it in the forum too :smile:

**Comment by philmmanjaro** [comment]
**catalyst** has an issue, that is why I download it with **wget** before. However the fix of the AUR package can be adopted to all **catalyst** PKGBUILDs. Was **mhwd-kernel** tested with this already? Else we have to think about a shorter name like **linuxrt** or such ...

**Comment by budimanjojo** [comment]
@philmmanjaro @oberon2007 has commited the fix in catalyst and it's now building fine. Thanks man.
I don't think mhwd-kernel works yet because it seems like it's hard coded to only search for kernels with the name linux[0-9][0-9]?([0-9]). But if the name is changed to linuxrt then maybe it'll be easier to integrate it with mhwd-kernel?

**Comment by oberon2007** [comment]
Right now **msm** thinks that I'm running **linux46** while it's actually **rt**...

**Comment by oberon2007** [comment]
I'll merge this now. That will make our lifes easier I think, no matter how we procede.

**Comment by budimanjojo** [comment]
@oberon2007 So when we got update, does msm install the linux46 when the user doesn't have linux46 installed?

**Comment by oberon2007** [comment]
No, since it will just be a package update and the package names differ for pacman.
It would just be awesome if we could make msm handle the rt kernel aswell. But I'm afraid Philip would have to make that possible for us... ... :no_mouth:

**Comment by budimanjojo** [comment]
Alright, that's good then. I think it's okay to install it manually for now. He's a busy man ☺

**Comment by budimanjojo** [comment]
@oberon2007 Now it's time for optimization. Here's what I found in the diff of linux-rt in AUR with linux from Arch kernel:
````3c3
< # Linux/x86 4.6.0 Kernel Configuration
---
> # Linux/x86 4.6.2 Kernel Configuration
25c25,26
< CONFIG_RWSEM_XCHGADD_ALGORITHM=y
---
> CONFIG_RWSEM_GENERIC_SPINLOCK=y
> # CONFIG_RWSEM_XCHGADD_ALGORITHM is not set
55,56c56,57
< CONFIG_LOCALVERSION="-ARCH"
< CONFIG_LOCALVERSION_AUTO=y
---
> CONFIG_LOCALVERSION="-rt"
> # CONFIG_LOCALVERSION_AUTO is not set
153d153
< # CONFIG_RT_GROUP_SCHED is not set
195c195
< # CONFIG_KALLSYMS_ALL is not set
---
> CONFIG_KALLSYMS_ALL=y
226d225
< # CONFIG_SLAB is not set
228d226
< CONFIG_SLUB_CPU_PARTIAL=y
233,234d230
< CONFIG_OPROFILE=m
< # CONFIG_OPROFILE_EVENT_MULTIPLEX is not set
238,239d233
< CONFIG_JUMP_LABEL=y
< # CONFIG_STATIC_KEYS_SELFTEST is not set
356d349
< CONFIG_UNINLINE_SPIN_UNLOCK=y
358,360d350
< CONFIG_MUTEX_SPIN_ON_OWNER=y
< CONFIG_RWSEM_SPIN_ON_OWNER=y
< CONFIG_LOCK_SPIN_ON_OWNER=y
439a430,433
> CONFIG_PREEMPT=y
> CONFIG_PREEMPT_RT_BASE=y
> CONFIG_HAVE_PREEMPT_LAZY=y
> CONFIG_PREEMPT_LAZY=y
442c436,438
< CONFIG_PREEMPT=y
---
> # CONFIG_PREEMPT__LL is not set
> # CONFIG_PREEMPT_RTB is not set
> CONFIG_PREEMPT_RT_FULL=y
503,505d498
< CONFIG_TRANSPARENT_HUGEPAGE=y
< CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS=y
< # CONFIG_TRANSPARENT_HUGEPAGE_MADVISE is not set
667d659
< CONFIG_X86_POWERNOW_K8=m
1952a1945
> CONFIG_HWLAT_DETECTOR=m
2333,2335d2325
< CONFIG_BCACHE=m
< # CONFIG_BCACHE_DEBUG is not set
< # CONFIG_BCACHE_CLOSURES_DEBUG is not set
6125d6114
< CONFIG_LEDS_TRIGGER_CPU=y
7643c7632
< # CONFIG_LATENCYTOP is not set
---
> CONFIG_LATENCYTOP=y
7661d7649
< CONFIG_RING_BUFFER_ALLOW_SWAP=y
7670a7659,7660
> CONFIG_WAKEUP_LATENCY_HIST=y
> # CONFIG_MISSED_TIMER_OFFSETS_HIST is not set

````
And then here's the diff of Manjaro linux46 and linux-rt config
````
3c3
< # Linux/x86 4.6.0-1 Kernel Configuration
---
> # Linux/x86 4.6.2 Kernel Configuration
25c25,26
< CONFIG_RWSEM_XCHGADD_ALGORITHM=y
---
> CONFIG_RWSEM_GENERIC_SPINLOCK=y
> # CONFIG_RWSEM_XCHGADD_ALGORITHM is not set
55,56c56,57
< CONFIG_LOCALVERSION="-MANJARO"
< CONFIG_LOCALVERSION_AUTO=y
---
> CONFIG_LOCALVERSION="-rt"
> # CONFIG_LOCALVERSION_AUTO is not set
153d153
< # CONFIG_RT_GROUP_SCHED is not set
195c195
< # CONFIG_KALLSYMS_ALL is not set
---
> CONFIG_KALLSYMS_ALL=y
226d225
< # CONFIG_SLAB is not set
228d226
< CONFIG_SLUB_CPU_PARTIAL=y
233,234d230
< CONFIG_OPROFILE=m
< # CONFIG_OPROFILE_EVENT_MULTIPLEX is not set
238,239d233
< CONFIG_JUMP_LABEL=y
< # CONFIG_STATIC_KEYS_SELFTEST is not set
349,351d342
< CONFIG_IOSCHED_BFQ=y
< CONFIG_BFQ_GROUP_IOSCHED=y
< CONFIG_CGROUP_BFQIO=y
353,354c344
< # CONFIG_DEFAULT_CFQ is not set
< CONFIG_DEFAULT_BFQ=y
---
> CONFIG_DEFAULT_CFQ=y
356c346
< CONFIG_DEFAULT_IOSCHED="bfq"
---
> CONFIG_DEFAULT_IOSCHED="cfq"
360d349
< CONFIG_UNINLINE_SPIN_UNLOCK=y
362,364d350
< CONFIG_MUTEX_SPIN_ON_OWNER=y
< CONFIG_RWSEM_SPIN_ON_OWNER=y
< CONFIG_LOCK_SPIN_ON_OWNER=y
443a430,433
> CONFIG_PREEMPT=y
> CONFIG_PREEMPT_RT_BASE=y
> CONFIG_HAVE_PREEMPT_LAZY=y
> CONFIG_PREEMPT_LAZY=y
446c436,438
< CONFIG_PREEMPT=y
---
> # CONFIG_PREEMPT__LL is not set
> # CONFIG_PREEMPT_RTB is not set
> CONFIG_PREEMPT_RT_FULL=y
507,509d498
< CONFIG_TRANSPARENT_HUGEPAGE=y
< CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS=y
< # CONFIG_TRANSPARENT_HUGEPAGE_MADVISE is not set
671d659
< CONFIG_X86_POWERNOW_K8=m
1956a1945
> CONFIG_HWLAT_DETECTOR=m
2337,2339d2325
< CONFIG_BCACHE=m
< # CONFIG_BCACHE_DEBUG is not set
< # CONFIG_BCACHE_CLOSURES_DEBUG is not set
5065c5051
< CONFIG_DRM_AMDGPU_CIK=y
---
> # CONFIG_DRM_AMDGPU_CIK is not set
6129d6114
< CONFIG_LEDS_TRIGGER_CPU=y
6321,6322c6306,6307
< CONFIG_DW_DMAC_CORE=m
< CONFIG_DW_DMAC=m
---
> CONFIG_DW_DMAC_CORE=y
> CONFIG_DW_DMAC=y
7647c7632
< # CONFIG_LATENCYTOP is not set
---
> CONFIG_LATENCYTOP=y
7665d7649
< CONFIG_RING_BUFFER_ALLOW_SWAP=y
7674a7659,7660
> CONFIG_WAKEUP_LATENCY_HIST=y
> # CONFIG_MISSED_TIMER_OFFSETS_HIST is not set
````
So , this is what I'm gonna add in the PKGBUILD and config.rt file:
````
diff --git a/linux-rt-manjaro/PKGBUILD b/linux-rt-manjaro/PKGBUILD
index bd0d262..1a5a6d3 100644
--- a/linux-rt-manjaro/PKGBUILD
+++ b/linux-rt-manjaro/PKGBUILD
@@ -148,6 +148,15 @@ prepare() {
   sed -i "s|# CONFIG_HZ_1000 is not set|CONFIG_HZ_1000=y|g" ./.config
   sed -i "s|CONFIG_HZ=300|CONFIG_HZ=1000|g" ./.config
 
+  # Add support for latencytop to test latency
+  sed -i "s|# CONFIG_LATENCYTOP is not set|CONFIG_LATENCYTOP=y|g" ./.config
+
+  # Match linux-rt config
+  awk '!/CONFIG_UNINLINE_SPIN_UNLOCK=y/' ./config > temp && mv temp ./config
+  awk '!/CONFIG_MUTEX_SPIN_ON_OWNER=y/' ./config > temp && mv temp ./config
+  awk '!/CONFIG_RWSEM_SPIN_ON_OWNER=y/' ./config > temp && mv temp ./config
+  awk '!CONFIG_LOCK_SPIN_ON_OWNER=y/' ./config > temp && mv temp ./config
+
   if [ "${_kernelname}" != "" ]; then
     sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"-MANJARO\"|g" ./.config
     sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
diff --git a/linux-rt-manjaro/config.rt b/linux-rt-manjaro/config.rt
index ad6755f..71b8a22 100644
--- a/linux-rt-manjaro/config.rt
+++ b/linux-rt-manjaro/config.rt
@@ -1,9 +1,11 @@
 CONFIG_PREEMPT_RT_FULL=y
-CONFIG_PREEMPT_RT_FULL_AUTOPROBE=y
+CONFIG_PREEMPT_RT_BASE=y
+CONFIG_HAVE_PREEMPT_LAZY=y
+CONFIG_PREEMPT_LAZY=y
 # CONFIG_PREEMPT_NONE is not set
 # CONFIG_PREEMPT_VOLUNTARY is not set
 # CONFIG_PREEMPT__LL is not set
 # CONFIG_PREEMPT_RTB is not set
-CONFIG_HWLAT_DETECTOR=y
-# CONFIG_WAKEUP_LATENCY_HIST is not set
+CONFIG_HWLAT_DETECTOR=m
+CONFIG_WAKEUP_LATENCY_HIST=y
 # CONFIG_MISSED_TIMER_OFFSETS_HIST is not set
````
What do you guys think?

**Comment by oberon2007** [comment]
ok. let's try that.

**Comment by oberon2007** [comment]
The **config** you don't need to change from the PKGBUILD. Just edit it in the repo.

**Comment by budimanjojo** [comment]
@oberon2007 Alright, I'm gonna commit them into my repo first later and test it out myself. 
I want to keep the main config as clean as possible, so it's easier when there's a new default config for the new kernel update. Actually just found out I missed one dot in ./config, should be ./.config 😅

**Comment by oberon2007** [comment]
Your awk commands are not really working. Removing lines I think is easier with sed, something like
``sed -i "/CONFIG_UNINLINE_SPIN_UNLOCK/d" ./.config``
will do the same :wink: 
However, the kernel doesn't like this config just like that - I guess some of them are contradicting each other. We'll have to look more in what exactly they are doing! ... :stuck_out_tongue_winking_eye: 
```
make[2]: *** [scripts/kconfig/Makefile:38: silentoldconfig] Error 1
make[1]: *** [Makefile:538: silentoldconfig] Error 2
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
```

**Comment by budimanjojo** [comment]
@oberon2007 just found out. I'm currently building here. :smile: 
Pushed a new commit there. Seems like I got a new config here, CONFIG_LIVEPATCH (new) suddenly appeared out of nowhere, I don't know why did it come out now but not before this commit. Weird

**Comment by budimanjojo** [comment]
I don't understand sed command so much, I tried another sed command in terminal before using awk and it's taking too long to delete a line in such a big file. Maybe it's just me?

**Comment by budimanjojo** [comment]
Alright, seems like I just used the wrong sed argument before. Commited, now with sed instead of awk :smile:

**Comment by philmmanjaro** [comment]
For now **mhwd-kernel** only [checks for kernels](https://github.com/manjaro/mhwd/commit/47fef5a6b0dcdca408c2d913c730e507036d96c7) in our **core** repository. When we have a final name scheme we can think about integrating also community kernels into mhwd.

**Comment by oberon2007** [comment]
The error in reasoning here was that we actually must not compare the **config** files but the effective **.config** files after all the patches have been applied. Then it looks more [**like this**!!](https://github.com/oberon2007/manjaro-rt/blob/master/.config.diff) :stuck_out_tongue_winking_eye: 
It will needs to be well considered what you really want to change there ... ... :wink:

**Comment by budimanjojo** [comment]
@oberon2007 Where's the spin_unlock and friends deletion? Also the new rt_base preempt_lazy etc is not there. Is the config.rt applied?

**Comment by budimanjojo** [comment]
There was no error, it just ask me to configure the CONFIG_LIVEPATCH. The weird thing is I didn't delete the line the config file and there's no such line in the config and config.x86_64. So I found it weird that the new config just appeared out of nowhere 😁

**Comment by oberon2007** [comment]
The diff was between official manjaro linux46 and the linux-rt from the AUR! :wink:
I'll open a proper issue for further discussion: https://github.com/manjaro/packages-community/issues/new

**Comment by budimanjojo** [comment]
@oberon2007 should we add this? https://github.com/manjaro/packages-core/commit/2d3418f9ef9fc043182d5ab7b946971075ce40e7

**Comment by budimanjojo** [comment]
Oh my God I was on the wrong branch, sorry but we don't need it. 😅

**Comment by oberon2007** [comment]
Ok fine ;) What about the aufs stuff though?

**Comment by budimanjojo** [comment]
It's not building at all with AUFS, but at least I was told that it's not needed though: https://forum.manjaro.org/t/rt-and-aufs-kernel-patch-hate-each-other/3738
Seems like filesystems those are not supported in the mainline kernel just don't work with rt patch. But at least overlayfs which is used by Manjaro live media is working so there's no problem here. ☺

**Comment by oberon2007** [comment]
Ah. I see. :)

**Comment by oberon2007** [comment]
And what's the deal about those thinkpad led and backlight patches? What's there origin? Should we think about adopting them in the regular manjaro-kernels aswell?

**Comment by budimanjojo** [comment]
Isn't it already there?
````
  # add Gentoo patches
  msg "1700_enable-thinkpad-micled.patch"
  patch -Np1 -i "${srcdir}/1700_enable-thinkpad-micled.patch"
  msg "2700_ThinkPad-30-brightness-control-fix.patch"
  patch -Np1 -i "${srcdir}/2700_ThinkPad-30-brightness-control-fix.patch"
````
That's from the manjaro linux46. All of the patches from the main manjaro kernel are included excluding AUFS :smile:

**Comment by budimanjojo** [comment]
Actually the msg "patchname.patch" lines are added by me, to simplify reading the error log if it fails :smile:

**Comment by oberon2007** [comment]
They are in your PKGBUILD, yes but not in the original linux46 one - that's what I mean!
btw I mixed up the tow livepatch lines and ``CONFIG_HAVE_LIVEPATCH=y`` can indeed be removed, you are right. It's the other one we need to keep, sorry! :laughing: 
btw. we can also get rid of these two for 64bit:
```
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
```
They're in **config.x86_64**, too

**Comment by budimanjojo** [comment]
Oh yeah I just noticed. They're inside the source= though, linux44 (which I begin with) has those patches. Maybe it's just Philm forgot to add them? Okay, delete all the duplicated items. 😆

**Comment by oberon2007** [comment]
Maybe thinkpad led and backlight patches are not needed since linux46? @philmmanjaro could you shed some light on this?

**Comment by budimanjojo** [comment]
I don't know, but maybe. Because it was there when it initially got inside the repo: https://github.com/manjaro/packages-core/commit/2ac8c9c7fe708fe088600213a9a43b920d2ffca9

**Comment by budimanjojo** [comment]
Can't find the commit where it got deleted though

**Comment by oberon2007** [comment]
Ah  of course, sorry my bad! :laughing: It is infact still there, just as an url and not in the repo. I didn't see it in the PKGBUILD with the label "gentoo patches" ;)

**Comment by budimanjojo** [comment]
Okay, ☺
Now I'm curious if the packages will get into stable branch on next update. Is it up to Philm?

**Comment by oberon2007** [comment]
The packages will be travelling the normal way into testing and then to stable. Right now there seems to be a pending snapshot from the current testing branch and I'm not sure if there will be another snapshot unstable > testing before the next stable update. In any case it has to happen synchronized with virtualbox 5.0.22, which is still in unstable branch...

**Comment by budimanjojo** [comment]
Okay, understood ☺

**Pull request merged**
