### PR TITLE
Update Hyper

### PR DESCRIPTION
**Pull request by codesardine**
this was taken from the aur

### CODE REVIEW

**Comment by Ste74** [comment]
This change ( pkgver name ) is recognized fine by pacman/wrapper the update ?

**Comment by philmmanjaro** [comment]
Is this a downgrade?

**Comment by codesardine** [comment]
Upgrade to latest pre release, stable version is 1.4.8 i guess we have to go up until hits stable 

more info here:
https://github.com/zeit/hyper/releases
https://aur.archlinux.org/packages/hyper/

**Comment by philmmanjaro** [comment]
OK, I added the needed epoch to it ...

**Comment by codesardine** [comment]
thanks :+1:

**Pull request merged**
