### PR TITLE
Add Manjaro Webdad Packages

### PR DESCRIPTION
**Pull request by codesardine**
Tested localy, everything seems to work fine

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Packages are now uploaded to **Manjaro-64** and **Manjaro-32**.

**Comment by codesardine** [comment]
Thanks, will do alpha4 build tomorow. :+1:

**Comment by philmmanjaro** [comment]
Vitor, looking forward to it. Uploaded to **unstable** branch for now. Will migrate to other branches via usual update process.

**Comment by codesardine** [comment]
No problem thanks.

**Comment by philmmanjaro** [comment]
Packages are now in our **testing** branch also ...

**Comment by codesardine** [comment]
theres is some conflits i need to fix, working on it

**Comment by codesardine** [comment]
could you rebuild: hopefully i can build an iso now
manjaro-webdad-settings
webdad-theming

**Comment by codesardine** [comment]
Hi everyone @philmmanjaro  @Ste74  @oberon2007 

could someone rebuild this 2 packages when possible, let me know when is done so i can test if the iso builds, cheers
manjaro-webdad-settings
webdad-theming

**Comment by Ste74** [comment]
`manjaro-webdad-settings`
return me an error 

> error: failed to commit transaction (conflicting files)
> webdad-theming-git: /usr/share/icons/default/index.theme exists in filesystem
> Errors occurred, no packages were upgraded.
> ==> ERROR: 'pacman' failed to install missing dependencies.
@codesardine needed solving the conflict ;)

**Comment by codesardine** [comment]
that is fixed, rebuild 
webdad-theming then rebuild manjaro-webdad-settings

**Comment by Ste74** [comment]
Done https://github.com/manjaro/packages-community/commit/748956839b15199a84838975427f08da992ed692

**Comment by codesardine** [comment]
thanks @Ste74 , doing a test iso now if all goes well, I will send a profile push to community editions

**Pull request merged**
