### PR TITLE
Add lightfirefox

### PR DESCRIPTION
**Pull request by Chrysostomus**
Lighter version of firefox with less dependencies and ram usage, to be used in bspwm edition. 

Would it be okay to add this? It builds by extracting from rpm package, so build time is quite short compared to actually compiling a browser.

### CODE REVIEW

**Comment by oberon2007** [comment]
I will try it :)
So, it's not conflicting with firefox and you can install both?
The install file can be removed - pacman hooks will take care of that.

**Comment by Chrysostomus** [comment]
Yeah, it can run alongside firefox. Binary is linked to /usr/bin/light

**Comment by Chrysostomus** [comment]
I removed the install file now.

**Comment by oberon2007** [comment]
Looking good! :)
Adding a symlinkg to the theme's Firefox chrome folder in **~/.light/light/xyz.default/** also works without problem. I will see if I can add the default manjaro bookmarks to the browser-settings package for **light**, too.

**Comment by Chrysostomus** [comment]
Nice, thanks!

**Comment by korrode** [comment]
Why do you prefer this over Pale Moon?

**Comment by Chrysostomus** [comment]
1) does not require gtk2. Thusfar bspwm edition has lacked a fully featured browser, because it does not have gtk2. This package gets around that.

2) merged urlbar and search bar by default.

3) closer to firefox and based on latest stable forefox version. Not a full fork, but just a build with some options disabled.

**Pull request merged**
