### PR TITLE
removes all .install commands that are now taken care of by pacman hooks 

### PR DESCRIPTION
**Pull request by oberon2007**
now accomplished by

- gconf-{install,remove}.hook
- glib-compile-schemes.hook
- gtk-update-icon-cache.hook
- texinfo-{install,remove}.hook
- update-desktop-database.hook
- update-mime-database.hook

### CODE REVIEW

**Comment by Ste74** [comment]
?? How to work now ?

**Comment by FadeMind** [comment]
@oberon2007 You want remove `grub-customizer` too?

**Comment by FadeMind** [comment]
@Ste74 FYI http://archlinux.2023198.n4.nabble.com/Hooks-td4710758.html

**Comment by oberon2007** [comment]
@FadeMind We agreed to remove **grub-customizer** a while ago already. it causes all sorts of problems and is available from the AUR for who still wants it.
@Ste74 have a look at the content of your **/usr/share/libalpm/hooks** directory! :wink: The actions are now triggered automatically when certain files are changed by packages.

**Comment by FadeMind** [comment]
@oberon2007 @Ste74 
https://wiki.archlinux.org/index.php/DeveloperWiki:Pacman_Hooks

**Comment by oberon2007** [comment]
```
/usr/share/libalpm/hooks/ is owned by desktop-file-utils 0.22-2
/usr/share/libalpm/hooks/ is owned by gconf 3.2.6-4
/usr/share/libalpm/hooks/ is owned by glib2 2.48.0-2
/usr/share/libalpm/hooks/ is owned by gtk-update-icon-cache 3.20.3-3
/usr/share/libalpm/hooks/ is owned by pacman 5.0.1-2
/usr/share/libalpm/hooks/ is owned by shared-mime-info 1.6-2
/usr/share/libalpm/hooks/ is owned by texinfo 6.1-3
```

**Comment by oberon2007** [comment]
```
ls /usr/share/libalpm/hooks/
gconf-install.hook
gconf-remove.hook
gio-querymodules.hook
glib-compile-schemes.hook
gtk-update-icon-cache.hook
texinfo-install.hook
texinfo-remove.hook
update-desktop-database.hook
update-mime-database.hook
```

**Comment by oberon2007** [comment]
So we can be sure that all the necessary hooks are installed by 'reliable' packages that will definitely be present.
I am surprised that we don't have that **fc-cache** hook, yet. I guess it will come...

**Comment by philmmanjaro** [comment]
We need to fix the conflicts before we can merge that.

**Comment by oberon2007** [comment]
It should be just FF-gtk2 I think. Shall I or are you doing it?

**Comment by philmmanjaro** [comment]
I think we remove the FF-gtk2 package. FF-KDE is already GTK3 ported. I'm at work, so I can't fix it. Feel free to do it.

**Pull request merged**
