### PR TITLE
Update Jade to 6.1

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by oberon-manjaro** [comment]
Folder name should reflect  actual  pkgname (or pkgbase).
Please check provides and replaces arrays.  They don't really make sense :wink:
pkgver() function can be removed or commented out for stable package

**Comment by oberon-manjaro** [comment]
I suspect there might be some general misunderstanding with how you use `replaces`. You might want to read [this](https://wiki.archlinux.org/index.php/PKGBUILD#replaces) :smile:

**Comment by codesardine** [comment]
ok is not stable yet, is now following tag release on github, anything missing?

**Comment by oberon-manjaro** [comment]
pkgrel should be 1, since we don't have a v0.6.1 in the repos, yet.
My question is again, why `replaces=('jade-dashboard')`?
In this case it doesn't hurt, but actually we never had a pkg **jade-dashboard**, or did we? So what are we replacing? :wink: 
I think what you actually mean is [`conflict`](https://wiki.archlinux.org/index.php/PKGBUILD#conflict), although also that would really make sense if a stable pkg actually existed.

**Comment by codesardine** [comment]
I think that should do it, you will like this version, comes with the manjaro logo.

**Comment by oberon-manjaro** [comment]
:+1:

**Comment by oberon-manjaro** [comment]
I have now moved the webdad packages to there own subgroup on our [gitlab](https://gitlab.manjaro.org/packages/community/webdad). Let me know in case I forgot something.

**Pull request merged**
