### PR TITLE
i-nex: 7.6.0 upstream update

### PR DESCRIPTION
**Pull request by FadeMind**

### CODE REVIEW

**Comment by oberon2007** [comment]
Thank you.

**Comment by oberon2007** [comment]
@FadeMind there seems to be a problem with creating the symling at the end of that **Makefile**:
```
gzip -9 "/build/i-nex/pkg/i-nex/usr/share/man/man1/i-nex-cpuid.1"
ln -s /usr/bin/i-nex.gambas /build/i-nex/pkg/i-nex/usr/bin/i-nex
make[2]: Entering directory '/build/i-nex/src/I-Nex/I-Nex'
make[2]: Nothing to be done for 'install-data-am'.
ln: failed to create symbolic link '/build/i-nex/pkg/i-nex/usr/bin/i-nex': No such file or directory
```

**Comment by FadeMind** [comment]
@oberon2007 package was built fine on my side. (Manjaro).

@eloaders CC

**Comment by oberon2007** [comment]
Uhm. Ok, this is weird. I just tried again without changing anything and it did in fact build here, too, without issue now - kind of mysterious...

**Comment by oberon2007** [comment]
In fact you have to run makepkg twice and it will work. I haven't fully understood why, yet ...

**Pull request merged**
