### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by Chrysostomus**
Lemonpanel has been updated to have more menuitems and now allows setting fonts through enviroment variables. It needs rebuilding.

### CODE REVIEW

**Comment by oberon2007** [comment]
If you'd like to put all files that go to **$pkgdir/usr/bin** in a folder named **/bin** in your git-repo, we could very nicely clean up the PKGBUILD like
```
install -Dm755 $srcdir/$pkgname/lemonpanel $pkgdir/usr/bin/lemonpanel
cp -r $srcdir/bin $pkgdir/usr
```
done ;)
Another advantage is when you add new scripts to the same folder they will automatically be copied aswell... :sunglasses:

**Comment by Chrysostomus** [comment]
Cool! Sounds awesome!

Will you clean up the pkgbuild if I put them to /bin? I can try it myself too, but I would rather see it once before trying, to be sure of the syntax.

We could do the same for bspwm-scripts too.

**Comment by oberon2007** [comment]
I can do that.

**Comment by Chrysostomus** [comment]
Ok, it is done on my end. The scripts of both repositories now rest in their respective /bin folders.

**Comment by oberon2007** [comment]
ok. PKGBUILDs are updated.
Could you please try to build/install them with ``makepkg -sri`` and verify that the file permissions are copied over correctly? If not you might have to make sure that the src-files are indeed executable.

**Comment by Chrysostomus** [comment]
I'll try it when I have a chance, I share computer with my wife.

**Comment by philmmanjaro** [comment]
To be sure please do this within the **PKGBUILD**. Simply add a line like: `chmod a+x $pkgdir/usr/bin/*`

**Comment by philmmanjaro** [comment]
23aacc725612516e97ab75fd25ba8633d592a1cf is a mess. Clean it up!

**Comment by oberon2007** [comment]
Yes. will have to add the ``chmod``. ``cp`` will just adopt the original permissions obviously...

**Pull request merged**
