### PR TITLE
Update bspwmrc

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by oberon2007** [comment]
Uhm, lines 80-83 are those '+' leftovers from some patch file and should I maybe remove them?

**Comment by oberon2007** [comment]
Or should they be '#'s? ;)

**Comment by philmmanjaro** [comment]
Please always verify before merging. I think the need to been removed ...

**Comment by oberon2007** [comment]
I saw it too late :stuck_out_tongue_closed_eyes: Maybe wait for @Chrysostomus 's answer? Maybe they are supposed to be commented out lines, don't you think?

**Comment by philmmanjaro** [comment]
Simply remove these double +s ;) https://github.com/Chrysostomus/packages-community/commit/3bb107ecdf43ab8ab68c0ddff489a091a2a75616

**Comment by oberon2007** [comment]
alles klar ;)

**Comment by Chrysostomus** [comment]
Sorry about the mess. I made changes first time using propose change function (my fork was nit up to date). I did not realize that + signs would get there with the changes.

**Comment by oberon2007** [comment]
No problem! :)

**Pull request merged**
