### PR TITLE
Manjaro lxde settings: change xfce4-notifyd to manjaro-lxde-xfce4-notifyd

### PR DESCRIPTION
**Pull request by ThanosApostolou**

### CODE REVIEW

**Comment by ThanosApostolou** [comment]
@oberon2007 Since I have created enough packages for lxde, should I move theme under a **lxde** folder so that they are easier to find. Will this make it easier for you to build them or harder?

**Comment by oberon2007** [comment]
I like that, yes. The list of packages in community is so long already...

**Comment by ThanosApostolou** [comment]
Ok I will do this on the same pull request so don't merge it yet.

**Comment by ThanosApostolou** [comment]
@oberon2007 I really made a mess with commits... github is harder to learn than it looks 😂 I think now it's ok. Please, give it a good look in case I have messed something up...

**Comment by oberon2007** [comment]
The content is fine. I'll close this anyway and do the changes in a clean commit 😉

**Comment by oberon2007** [comment]
almost... 🙄 😆

**Comment by ThanosApostolou** [comment]
You didn't delete the **manjaro-lxde-xfce4-notifyd-config.desktop** https://github.com/manjaro/packages-community/tree/master/manjaro-lxde-xfce4-notifyd

**Comment by oberon2007** [comment]
awesome 😝

**Comment by ThanosApostolou** [comment]
Haha i liked the "grrrr" description on the commit 😂  Now, if you can change **xfce4-notifyd** to **manjaro-lxde-xfce4-notifyd** dependency to **desktop-settings**, then pull the changes and build the **manjaro-lxde-settings** version **20170427** it would be great!

**Comment by oberon2007** [comment]
😉 was done already, just had not committted the change... 👍

**Comment by ThanosApostolou** [comment]
Perfect! I will write a comment in the manjaro lxde announcement in order to inform the forum about the changes/additions!

**Comment by oberon2007** [comment]
Just you know: I had pushed the initial change with the xfce4-notifyd dependency also to testing and stable branch - as an emergency measure sotosay... The latest changes are on unstable branch for now and will move with the other packages. I thought those adjustments were not really urgent...?

**Comment by ThanosApostolou** [comment]
Hmmm yeah it doesn't seem like anything urgent. People will get the xfce4-notifyd from the previous update so we are ok. I will just wright that when the 20170427 update gets into their repository, they will be able to change the **scrot** command to the **i3-scrot** in order to get notifications after screenshot.

**Pull request closed without merging**
