### PR TITLE
next gen steam client for manjaro

### PR DESCRIPTION
**Pull request by Tids**
Maybe you've heard that I was re-working the steam client packages for Manjaro. After the latest update the time is right to ship it (not as replacement, but as -next testing right now, since its not just a small change)

## steam-manjaro-next
* based on Archlinux' steam pkg with steam-manjaro patches 
* working Steamcontroller (our missing part was that we need to load uinput module before it'll work)
* cleanups

So for this I've bought the steamcontroller and make it work. It really was that simple, that we needed to set the rights to uinput in the udev files AND load uinput kmod. Thats why there is now the loader at /etc/modules-load.d/steam-uinput.conf to make sure we have it enabled when steam is installed.

the cleanups mostly where for some workarounds, like the mesa-patch that is not needed anymore, because since the steam update from 2016-01-19 it'll work with all the opensource drivers by default.

## steam-native-next
right now in Manjaros steam native client requires some libraries duplicates like lib32-libusb-steamruntime or lib32-libgudev-steamruntime that are not needed anymore in -next. It'll completely use the standard system runtime (thanks to archlinux work)

To make it more clean, it'll not create a secound launcher, but activates the option in the manjaro client to load the native runtime in the most simple way:
```
# Steam runtime settings
# if STEAM_RUNTIME=1, ignore this entirely
if [ "${STEAM_RUNTIME}" != "0" ]
    then
        # if steam-native package is installed, enable native runtime
        # and disable mesa-workarounds
        if [ -f "/usr/lib/steam/native_runtime.txt" ]
            then
                export STEAM_RUNTIME=0
                echo "Manjaro steam native configuration found!"
        fi
fi
```
That is needed because steam starts itself, when you launch a game via menu-entry and if we have 2 launcher "steam" & "steam-native" it'll launch steam with the steam runtime, even if native is installed. With my way it'll of course only use the native runtime, when it is installed.

~
However there is one issue left that somehow only appears on manjaro64. We need lib32-curl for steam-native-next but its not installable because of a symlink created by "something" (I really dont know) and links against lib32-libcurl-gnutls. So right now my only solution is 
```
pacman -Rnc lib32-libcurl-gnutls
pacman -Sy lib32-curl                                          
pacman -Sy lib32-libcurl-gnutls
```

----------------

Let's hope this work is OK. Like I've said - it would be nice if this could be included to manjaro for a bigger testing and if everything works, replace our current package with this.

-------

prebuild Versions, just in case 😉
[build.zip](https://github.com/manjaro/packages-community/files/719949/build.zip)

### CODE REVIEW

**Comment by Ste74** [comment]
Hi , i think lib32-libcurl-gnutls is shipped from our steam-native in our repo .. have you checked it ? In a minimal installation without steam pkgs is not present ..

**Comment by Kirek** [comment]
The issue with lib32-libcurl-gnutls is really weird.
0. Clean system, /usr/lib32/libcurl.so.4 is not present
1. Install lib32-libcurl-gnutls, no lib32-curl, /usr/lib32/libcurl.so.4 is present in the system and owned by no one. If you check the lib32-libcurl-gnutls package, the symlink is not there, so its generated by something.
2. Try installing lib32-curl, you can't because there is a conflicting file /usr/lib32/libcurl.so.4
3. Remove lib32-libcurl-gnutls, /usr/lib32/libcurl.so.4 owned by no one disappears
4. Now you can install lib32-curl, who owns /usr/lib32/libcurl.so.4
5. Install lib32-libcurl-gnutls, /usr/lib32/libcurl.so.4 is still owned by lib32-curl
6. Remove lib32-curl, /usr/lib32/libcurl.so.4 still in the filesystem but owned by NO ONE

This is fucking weird, is ldconfig creating this symlink?

**Comment by Kirek** [comment]
I think the steam-native-patch logic is wrong


```
[kirek@manjaro-vm ~]$ export STEAM_RUNTIME=1
[kirek@manjaro-vm ~]$ steam
Manjaro steam native configuration found!
Running Steam on manjarolinux 16.10 64-bit
STEAM_RUNTIME is disabled by the user
```

It should be:
```
if ! [ "${STEAM_RUNTIME}" == "1" ]
   then ...
```

**Comment by Tids** [comment]
@Kirek you're right about this. Thanks (:

@Ste74 
the issue here is when you install lib32-libcurl-gnutls alone, it will create some symlinks that prevents lib32-curl from installing. Inside the lib32-libcurl-gnutls package there is no symlink, no installation information about creating those symlinks and also no hook that will be triggered.

if you install lib32-libcurl at first and now lib32-libcurl-gnutls it will not create these symlinks and everything is fine.

**Comment by Ste74** [comment]
i have sent a request to reopen the issue on arch bugtrucker

**Comment by Ste74** [comment]
Well i think i merge it for easy big test into our community @Kirek if you are not in contrast i merge it ;)

**Comment by Kirek** [comment]
Can we change this to steam-manjaro and steam-native before merging?
I played a little with the package and seems fine.
Also let me push the packages myself to the repos because I want to make some changes to manjaro-system, lib32-libcurl-gnutls and lib32-libcurl-compat to avoid the conflicting file problems when upgrading.

**Comment by Ste74** [comment]
Honestly i can't test it because i have steam installed but no time to use 😉 .. Also for me is a no sense two pkgs for steam in our repo .. it create confusion in user .. and is also possible retard the introduction into stable .. But @Tids  seem more focalized with steam 😄

**Comment by Tids** [comment]
usually I'm OK with already renaming it, but in case there is something really broken with it - would it be possible to restore the old package "just in case" for unstable/and testing?

**Comment by Kirek** [comment]
Yes, we can do that if there are any problems

**Comment by Ste74** [comment]
Sure if really is broken and break the system is possible do a regression

**Comment by Tids** [comment]
if I didnt have missed something it should now be renamed completely. 🙃

**Comment by Kirek** [comment]
Thanks!

**Pull request merged**
