### PR TITLE
changed name from pacli-simple to pacui

### PR DESCRIPTION
**Pull request by excalibur1234**
i have not tested this new PKGBUILD, but it should work.

could somebody send me some commands, with which i can test, whether my PKGBUILD works?

### CODE REVIEW

**Comment by Ste74** [comment]
Maybe can you add also replace array to change automatically pacli in pacui.. and in aur you do the git version ? because if you do ok for the conlict but otherwise i think is not needed ..

**Comment by excalibur1234** [comment]
yes. the git version is in the AUR.

i have just added a "replaces" and will do another pull request now.

**Comment by Ste74** [comment]
Done 😄

**Comment by Ste74** [comment]
@excalibur1234 , i realize that : this is a new pkg.. you have do a release: you want continue to use the actual versioning or prefer follow your releasing ie ver 1.3 ?

**Comment by excalibur1234** [comment]
i would like to have version 1.3, because this is the same version i have released on github and on the AUR.

does this mean i have to remove "replaces".
or should i simply increase the pkgrel?

**Comment by Ste74** [comment]
Tonight i'm very crazy :) modified your pkgbuild to do what you want :)
https://github.com/manjaro/packages-community/commit/c6da496b0ada56abd51fe373f7a380f952bb3795

**Comment by excalibur1234** [comment]
thanks a lot.

one question: how did you create the md5sum? 
(what did you do to create it? git clone? which command to use?)

**Comment by oberon2007** [comment]
You can simply use ``updpkgsums`` command, which is part of **pacman** package :wink:

**Pull request merged**
