### PR TITLE
[mhwd-addon-amdgfx-hwe] refactoring & cleanup

### PR DESCRIPTION
**Pull request by Tids**
This is a cleanup of the amdgpu-hwe package.

It removes the listgen script, tht has generated the pciid files for mhwd. Those files are nor generated at makepkg-time.
It also removed the catalystuninstallation script (we dont need it anymore)
It also dont dont creates xorg-config files - the default (no config) is the best we can have
It also adds a video-intel+ script, for hybrid systems)

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@Tids: please check the **mhwd** changes in regard of **libgl** changes and adopt.

**Comment by Tids** [comment]
Done. I've added a --check instead.
Don't know if this is usefull, but it will also not harm anyone :)

**Comment by philmmanjaro** [comment]
@Tids: just ping me when I should merge this one.

**Comment by philmmanjaro** [comment]
@Tids: any update on this one?

**Comment by Tids** [comment]
Not right now. I'm planning a little test-session tomorrow, to make sure it still works. I'll ping you if everything works :)

**Comment by philmmanjaro** [comment]
@Tids: this makes sense. Waiting for your feedback then.

**Comment by Tids** [comment]
@philmmanjaro it took a bit longer but now it is tested and ready for the merge 👍 :)

**Pull request merged**
