### PR TITLE
Add the extras from ubuntu budgie

### PR DESCRIPTION
**Pull request by boredland**
As discussed here https://github.com/manjaro/iso-profiles/issues/109

### CODE REVIEW

**Comment by boredland** [comment]
Then we'd have to wait for this commit making it to a release, since it doesn't even work without it.
https://github.com/UbuntuBudgie/budgie-extras/commit/a49b2998701c3426668f5853611ed1d6cb65da05

**Comment by Ste74** [comment]
Not really, we can grab from commit like this example 
https://github.com/manjaro/packages-community/commit/8270c88d0fa022756a818eb70c13a6452b86b972#diff-d2e4f4f79d57931fd681ffc607b0038a
:wink:

**Comment by boredland** [comment]
Does https://github.com/manjaro/packages-community/pull/461/commits/72534db6418fb4b9242c1da9c7104add6b30fc0d meet that request?

**Comment by Ste74** [comment]
Done, thank you :smile:

**Pull request merged**
