### PR TITLE
Add Cudatext

### PR DESCRIPTION
**Pull request by liberodark**
Hello,

I keep this package on aur.
Being a manjaro user I prefer to keep it on your github.
And is good software for replace sublime text.
And have lexer for edit pkgbuild :D 

Cordialy

### CODE REVIEW

**Comment by Ste74** [comment]
What is the benefit for Manjaro with this package since is already present in AUR and you maintain it ?

**Comment by liberodark** [comment]
the advantage and the same as for atom why propose atom and not an alternative easier and faster than atom?

**Comment by liberodark** [comment]
I really think you should not trust Aur.
Because it raises remember the worries and it is harder you would tell me there is mur and amar.
But even so, I find that there are a lot of anti manjaro

**Comment by jonathonf** [comment]
The package version listed in the PR PKGBUILD is out-of-date (1.38.0 vs 1.38.3). The AUR package itself has two votes. The PKGBUILD file in its GitHub project is also out-of-date (1.22).

I can't see any reason for putting this in the repos.

**Comment by Chrysostomus** [comment]
I'll test it. There seems to be many reasons not to include it, but if it really is a viable sublime-text alternative then I might be willing to maintain it. Would prefer to build it from source though.

**Comment by Chrysostomus** [comment]
Are those dependencies correct? No qt, gtk or anything?

**Comment by Chrysostomus** [comment]
Okay, it seems that the pkgbuild is actually broken as the source .deb file is no longer available. Looking at how cumbersome it seems to compile, I can kinda see why precompiled version was used. I currently lack the time to write a proper PKGBUILD for it from scratch (would take a while with no prior knowledge in lazarus). Also, it seems that it uses qt4 in linux? I'm not very interested in qt at the moment, one of the reasons I like sublime-text is that it is gtk (sadly gtk2). 

All things considered, I would not adopt this. If you can provide me with a working PKGBUILD to test, then I'll reconsider.

**Comment by jonathonf** [comment]
If the provided PKGBUILD doesn't work this can't be merged anyway.

**Comment by Chrysostomus** [comment]
The PKGBUILD in aur seems work again. The dependencies are still not listed properly. It is gtk2 version, but it seems there is gtk3 version available somewhere too. A bit lighter even than sublime, not quite as smart, although I suspect that is because it needs some unlisted python dependency. Surprisingly small for what it is. If the extensions start working and gtk3 version is found, I might consider it.

**Pull request closed without merging**
