### PR TITLE
Creating a package that changes lxde default logout banner

### PR DESCRIPTION
**Pull request by ThanosApostolou**
@oberon2007 The change that we did on iso-profiles for changing the lxde logout banner works fine. However, I don't like putting files on `/usr/` directory without belonging to any package. So, I thought it would be more professional to do a package for that, which will be listed as dependency for `manjaro-lxde-settings` package.

Advantages I can think of:
1) I can change the logout banner automatically with a future update without needing use interference (which is appropriate behavior since the logout banner is a system's file not a user's configuration one).
2) Someone can just uninstall this package if he doesn't like my modifications without needing to search what files we manually changed.

### CODE REVIEW

**Comment by oberon2007** [comment]
Perfect! Good thinking!
Don't do
``mkdir -p $pkgdir/usr/local/bin`` - you have no control over permissions``
Instead just do
``install -Dm755 lxde-logout $pkgdir/usr/local/bin/lxde-logout``

**Comment by ThanosApostolou** [comment]
I didn't change the `mkdir -p $pkgdir/usr/share/lxde/images` since this will have already be created by `lxde-common` which I have as dependency. Tell if I should changed that too.

I haven't really understood how packages are created on manjaro. If this PR is accepted then the packages will automatically be created? Or do I need to do another PR somewhere so that this can be pushed to unstable branch and then for testing and stable as well?

**Comment by oberon2007** [comment]
same for the image file, 😉 
**/manjaro-lxde-settings-20170404** is already on unstable branch now.

**Comment by oberon2007** [comment]
> since this will have already be created by lxde-common

That's true for target system, but the package doesn't know! 
> packages will automatically be created?

One of the packagers will package it - normally the one who merges your commit.
Then we push the pkg to unstable and it travels with the snapshots together with all the othe pkgs to testing and stable.
In some cases if a package is needed on another branch earlier - for example if we want to build testing or stable ISOs we can forward packages also if needed.

**Pull request merged**
