### PR TITLE
firefox-kde/gtk2 46.0-1

### PR DESCRIPTION
**Pull request by FadeMind**
@Kirek @philmmanjaro @oberon2007 
Upstream Mozilla apps update

NOTE: I did not removing .install files against pacman hooks in this commit. I saw separated branch for this task.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
Firefox is using `gtk-update-icon-cache -q -t -f usr/share/icons/hicolor` in its install file. Therefore we can remove the install file on this one. However we have to check @oberon2007 branch to confirm the install files there getting removed are really with the hooks currently available.

**Comment by oberon2007** [comment]
@philmmanjaro see my other PR: https://github.com/manjaro/packages-community/pull/165

**Comment by oberon2007** [comment]
I have checked, but please someone confirm!

**Comment by Kirek** [comment]
I already have this updated locally, with other small changes.

**Pull request closed without merging**
