### PR TITLE
Update manjaro.diff

### PR DESCRIPTION
**Pull request by 7yber**
Year passed

### CODE REVIEW

**Comment by oberon2007** [comment]
I'm trying to limit the information in statusbar to the essential information. Since the current year doesn't change so ofter, I decided to leave that out ;) I don't think we should include it by default.

**Comment by 7yber** [comment]
Maybe. For me it is better to cut "cpu", "no lan", "no wlan" than cut year info.

**Comment by oberon2007** [comment]
It's individual preference of course. In any case, just something for the user to get started with and you will have to adjust it anyway. The network is a good example. Personally I display only wifi and no lan because I almost never use wired network. But it's good to have the setting there so you don't have to investigate when you need it... :)

**Comment by oberon2007** [comment]
Apart from that, the default screen has s conky displaying the date including year already.

**Pull request closed without merging**
