### PR TITLE
Add Breeze-maia-gtk3 and terminusfix

### PR DESCRIPTION
**Pull request by Chrysostomus**

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Terminus is used all over the bspwm edition, and freetype changing its name kind of messes the whole desktop up. This is to ward off that.

Breeze-maia-gtk3 is just breeze-gtk trimmed down and blue colors switched to maia green. I might be using it in the next release of bspwm edition.

**Comment by Kirek** [comment]
What's the difference with breeze-maia-gtk3 and https://github.com/manjaro/packages-community/tree/master/gtk-theme-maia ? The later is also based on breeze-gtk

**Comment by Chrysostomus** [comment]
It has the dark theme variant: https://forum.manjaro.org/t/just-january-screenshots/14936/90

But now that I realize there is also gtk-theme-maia, I think it would be better to just add the dark variant to it. Could we merge the packages?

**Comment by Kirek** [comment]
I will add the dark variant to the artwork-maia-gtk repo and modify the package to include it. It's that okay?

**Comment by Chrysostomus** [comment]
That would be great! Thanks!

**Comment by oberon2007** [comment]
I think it would be much better to create an overlay package of **terminus-font** with the alias file included - won't be much maintenance work - the package hasn't been updated for over a year now... ;)

**Comment by oberon2007** [comment]
Like that everyone will just benefit from the fix and in case the issue gets solved elsewhere we can simply remove the overlay again.

**Comment by Chrysostomus** [comment]
It's ok for me. Probably best that way.

**Comment by Kirek** [comment]
I'm okay with it. Remember to remove terminuxfix as I already pushed it.

**Comment by oberon2007** [comment]
Yes. With ``install -Dm755`` that pkg is not gonna work anyway, btw ;)
But apart from that, I have just tried [like this](https://github.com/manjaro/packages-community/blob/master/terminus-font/PKGBUILD) and still I cannot select "Terminus" in **lxappearance**?

**Comment by Chrysostomus** [comment]
It doesn't need to be selectable from lxappearance. It just needs to work from .dmenurc, because having a spaced font there breaks dmenu_recency. If you go to lxappearance, you can select a font by its right name anyway.

**Comment by oberon2007** [comment]
I see...  So can you confirm that the package the way it is now fixes the issue for you?

**Comment by Chrysostomus** [comment]
Yes. I have in my. dmenurc font "Terminus-15". Without the package, some fallback font is used. If I have 'xos4 Terminus' in .dmenurc,  dmenu_recency fails to load completely. If I pass that font directly from command line, dmenu_recency loads, but the submenu (terminal, background, terminal_hold) uses a different, smaller font.

**Pull request merged**
