### PR TITLE
Update thunar-shares-plugin-manjaro

### PR DESCRIPTION
**Pull request by LaLadaLa**
Bug fix: GID 617 - It already exists on my computer + small changes.

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@oberon2007: it seems make sense to merge this one.

**Comment by oberon2007** [comment]
I don't know about samba... If it looks right to you, go ahead! 👍

**Comment by spsf64** [comment]
Please also change in smb.conf  workgroup = WORKGROUP (instead of MANJARO) because many routers with samba capability do use WORKGROUP name hardcoded in firmware, so you end up with 2 different names in the network.

**Comment by Ste74** [comment]
@philmmanjaro see here : https://github.com/manjaro/packages-extra/commit/d39fa801724684ea0b82731b63e1b574f5c17fc3
added a smb.conf general for general purpos.. link to our forum tread in the comment-commit .. not pushed , if ok i correct the pkgbuild ( since note now this thunar plugin provide a smb.conf :p ) or correct this to depend on my smb.conf .. i push this evening ..
@spsf64 the workgroup array is not important because is only the name of the network.. samba scan all network and show the name so if the protocol is right you see manjaro and workgroup in the list ..

**Comment by spsf64** [comment]
@Ste74 Thats is the problem, I always end up with 2 names on the network, I think for the end user just "Workgroup" would be a better/easier to understand...
TIA

**Pull request merged**
