### PR TITLE
Update Hyper and Webdad

### PR DESCRIPTION
**Pull request by codesardine**

### CODE REVIEW

**Comment by codesardine** [comment]
I only have on more issue to resolve.

The files lighdm.conf and slick-greeter.conf in the iso profile /etc/lighdm/  get overrriden when i update lightdm or slick greeter.

I could create a systemd script that copys them over on startup.
Any better way of doing this?

**Comment by Ste74** [comment]
What you mean ? Any of our editions where use this files don't reset the configuration at the firs update..

**Comment by codesardine** [comment]
I got the iso profile with a custom /etc/lightdm/slick-greeter.conf

the package slick-greeter also have a /etc/lightdm/slick-greeter.conf, wont this file get updated when i receive a slick-greeter update ?

**Comment by Ste74** [comment]
No, if you have build the iso with your custom .conf we don't modify the script .. pacman save the new .conf  ( if upstream is changed)  in a pacnew file ;)

**Comment by codesardine** [comment]
Ha I dint'd know that thanks :+1:

**Pull request merged**
